### ISSUE TITLE
Spawner does not drop upon Silk Touch.

### ISSUE THREAD

**Issue by dotParx** [The-Nexus-Project/Limitless-3#10]
### Describe your issue, what happened?
The description **Spawner** in JEI states that they can be silk touched.
Doing so still results in a spawner shard dropping and not the spawner itself.

### To Reproduce
1. Search "Spawner" in JEI
2. Click on 'info'
3. Read the last line.
4. Locate spawner and mine with silk touch.

### Expected behavior
The spawner would drop as described.
Alternatively the info would not state the spawners will drop on silk touch..

### Affected Version

- Pack Version: 1.5.0
- On a server?: Yes (Happens in single player as well)

**Comment by Gbergz** [comment]
Thanks for the report!
