### ISSUE TITLE
Crash occurring with jetpacks

### ISSUE THREAD

**Issue by SmolBlob** [The-Nexus-Project/Limitless-3#103]
Since the update we've noticed our server straight up crashes whenever someone engages using the jetpack- pressing v to turn it on or off seems to instantly crash the server and we have no idea why as these were working perfectly fine before the major update. Is there a fix for this that we don't know of? we've tried not using the back slot and using the chest plate slot instead but it still seems to be a very unstable thing.

**Comment by Gbergz** [comment]
Check closed issues next time.
https://github.com/The-Nexus-Project/Limitless-3/issues/100
