### ISSUE TITLE
Failed to launch game

### ISSUE THREAD

**Issue by TGMax233Michael** [The-Nexus-Project/Limitless-3#104]
### Describe your issue, what happened?
Failed to launch game (macOS system & multimc launcher)
[_I really wan to play this modpack,pls help me_]

### To Reproduce
1. No mods were added, set 7G memory allocation
2. Game Crashed when launching

### Expected behavior
Nothing

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/x90VxScT

### Affected Version
- Pack Version: 1.9.1a
- On a server?:no

**Comment by Avakining** [comment]
I'm getting the same issue on version 1.9.3 using the Curseforge app. 

One possible issue is whatever mod is potentially changing the title of the window -- a mod "It's The Little Things" did the same thing to [another modpack](https://github.com/mahjerion/Craft-to-Exile-Dissonance/issues/21) by changing the window title. I don't know for sure that's the issue, though.

Log: https://pastebin.com/B6SMxUWa
Java Crash Report: https://pastebin.com/5wLCvnLz
