### ISSUE TITLE
World Crash with ElementalCraft

### ISSUE THREAD

**Issue by Crysis27** [The-Nexus-Project/Limitless-3#105]
I reproduced 2 times a crash trying to craft Swift Alloy Ingor in the Element Binder.

I attach the crash report here.
[crash-2021-01-23_15.50.12-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5860458/crash-2021-01-23_15.50.12-server.txt)

**Comment by Solxanich** [comment]
Ran into this issue myself; updating to version 2.5.5 of elemental craft fixed it.

**Comment by Gbergz** [comment]
fixed next pack update

**Comment by Crysis27** [comment]
Thank you so much, u're awesome!
