### ISSUE TITLE
Game crash when using jetpack in curious body slot

### ISSUE THREAD

**Issue by JediAvenger** [The-Nexus-Project/Limitless-3#106]
### Describe your issue, what happened?
Game crashes when engaging jetpack positioned in curious body slot.

### To Reproduce

1. equip jetpack in curious body slot
2. turn on
3. game crashes

### Expected behavior
1. flight

### Found fix
1.  updated Curious Jetpacks mod to version 1.4
2. fixed crash issue

### Affected Version
Curious Jetpacks 1.3c
- Pack Version: 1.9.1a
- On a server?:

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-3/issues/100
