### ISSUE TITLE
Rats cannot move to hostile mobs (if fighting addon is used and set to hunt monsters) or to mine some cobble to get to nearby ore (with miner upgrade)

### ISSUE THREAD

**Issue by ghost** [The-Nexus-Project/Limitless-3#107]
### To Reproduce

only it happens on server

### Affected Version

- Pack Version:  1.9.1a
- On a server?: yes

**Comment by ghost** [comment]
Also if you try to open rat inventory to pick upgrade it will crash server

**Comment by Gbergz** [comment]
need more info, also report it here https://github.com/Alex-the-666/Rats/issues
