### ISSUE TITLE
Quests syncing not working

### ISSUE THREAD

**Issue by InferusAnima** [The-Nexus-Project/Limitless-3#109]
### Describe your issue, what happened?
Quest syncing not working, i added friend to team (ftbteams), but quests still not syncing.

### To Reproduce
1. /ftbteams invite "nickname"
2. complete any quest
### Expected behavior
When i got quest, my friend also should get it.

### Affected Version
- Pack Version: 1.8.5a
- On a server?: yes

**Comment by Gbergz** [comment]
Known issue. It's a FTB Teams / FTB Quests issue. Can't fix it on our end.

**Comment by InferusAnima** [comment]
k, thx for the response, i'll create issue theere.

**Comment by Gbergz** [comment]
No need, they already know about it.

**Comment by InferusAnima** [comment]
what's the point of mod, which purpose is to sync quests and it's not working :/

**Comment by InferusAnima** [comment]
> No need, they already know about it.

Is there a way to fix it rn?

**Comment by Gbergz** [comment]
Nope unfortunately.

**Comment by InferusAnima** [comment]
On 1.16.5 either?

**Comment by Gbergz** [comment]
It'll be fixed on 1.16.x when it's fixed.

**Comment by InferusAnima** [comment]
Got it, thx

**Comment by InferusAnima** [comment]
Is it working on 1.15.2?

**Comment by Gbergz** [comment]
No
