### ISSUE TITLE
Quest Eye Spy not completing

### ISSUE THREAD

**Issue by AugustDoctor** [The-Nexus-Project/Limitless-3#110]
### Describe your issue, what happened?
When trying to complete the quest Eye Spy it just doesn't. The advancement activates but the quest doesn't complete. We have tried multiple ways to complete by throwing the eye of ender normally and just dropping it and picking it up. Nothing works.

### Expected behavior
The quest to complete

### Affected Version

- Pack Version: 1.8.5
- On a server?: yes

**Comment by Gbergz** [comment]
I remember fixing this in the past. It does work and complete in v1.9.1a

**Comment by AugustDoctor** [comment]
Awesome we just updated to that. Thank you!
