### ISSUE TITLE
Extended Caves Crash issue. 1.9.1a

### ISSUE THREAD

**Issue by BlackflyCanada** [The-Nexus-Project/Limitless-3#111]
Seems the Dungeons that spawn skeletons in Extended Caves is causing a server crash.

I'm not using Optifine. Attacking or going near the Skeletons that spawn in those dungeons causes my server to crash, or have a stackoverflow error.

I have 11 gigs allocated to the server. I stopped them from spawning, but large areas have already been explored.

**Comment by Capt-efficiency** [comment]
If it's just skeletons causing the crash, check the log. It could be to do with blood magic. There have been a few crashes caused by it. 

Try disabling the mod and repeating what you did. That fixed the problem for me.

**Comment by Gbergz** [comment]
Fixed next update.
