### ISSUE TITLE
Server Tick with bloodmagic

### ISSUE THREAD

**Issue by Talidorn** [The-Nexus-Project/Limitless-3#113]
### Describe your issue, what happened?
Server ticking crash - java.lang.NullPointerException: Ticking entity

### To Reproduce
1. Go to one of those caged spawner two-story buildings.
2. Stand there for a few minutes
3. Server crashes.
4. Only fix is to TP the player away as they log in.
5. Bloodmagic mod owner says if the error is in a pack to open a ticket with pack dev and not bloodmagic.

### Expected behavior
No crash due to ticking entitiy

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://paste.ee/p/tu8V7

### Affected Version
1.9.1.a

**Comment by Gbergz** [comment]
Fixed next update
