### ISSUE TITLE
No Iron Ore processing recipe for Immersive Engineering Crusher

### ISSUE THREAD

**Issue by Spectre96** [The-Nexus-Project/Limitless-3#115]
### Describe your issue, what happened?
The Immersive Engineering Crusher does not have recipes to process Iron Ore.

### To Reproduce
Check JEI or insert any variant of Iron Ore into an Immersive Engineering Crusher

### Expected behavior
The Iron Ore is processed into Iron Dust.

### Screenshots
Gold Ore to Gold Dust recipe in JEI (Crusher tab located between Arc Furnace and Information)
![image](https://user-images.githubusercontent.com/78063720/105939319-31717c00-6016-11eb-8077-10e3e07624e6.png)
Iron Ore to Iron Dust recipe missing in JEI (No Crusher tab present)
![image](https://user-images.githubusercontent.com/78063720/105939371-4bab5a00-6016-11eb-9806-0ab7bd3b876b.png)

### Affected Version
- Pack Version: 1.9.2, issue was also present on 1.9.1a
- On a server?: Yes

**Comment by Gbergz** [comment]
Fixed next update! Thanks for the report.
