### ISSUE TITLE
Crashing Sound Muffler.

### ISSUE THREAD

**Issue by Crysis27** [The-Nexus-Project/Limitless-3#116]
I play with my friends via Hamachi, and whenever I open the wolrd in LAN and click the sound muffler button or hit the keybind, the world crashes. 

[crash-2021-01-27_16.55.36-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5881767/crash-2021-01-27_16.55.36-client.txt)

**Comment by Gbergz** [comment]
What pack version are you using? 
This has been reported on their github and is fixed in newer versions.
