### ISSUE TITLE
Crashing when getting certain status effects

### ISSUE THREAD

**Issue by KeenJames** [The-Nexus-Project/Limitless-3#117]
So I have crashed a few times due to status effects.  The first 2 times were caused by me getting poisoned from eating certain foods like a spider eye.  The fix I found was going in and editing my played data to remove the status effect. The more recent one that goes with this crash report happened while fighting wither skeletons and I got hit with a bunch of debuffs at once and don't know which one caused it.

[crash-2021-01-29_13.05.01-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5895861/crash-2021-01-29_13.05.01-server.txt)

**Comment by Sinyc1657** [comment]
I'm not sure if it's actually the same issue but I believe I've been having this problem on my server--though in my case it happens (I think?  I can't read crash reports that well) to a skeleton I assume is spawned via some kind of modded spawner.  It persists until I move the player loading the chunks to another location.
[crash-2021-02-02_12.17.08-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5914283/crash-2021-02-02_12.17.08-server.txt)

**Comment by r-mc2** [comment]
@KeenJames By chance were you wearing EnigmaticLegacy's Blazing Core charm?
There was a bug reported to them recently that has a similar crashlog:
https://github.com/Aizistral-Studios/Enigmatic-Legacy/issues/143

From how that bug sounds to work is the Core is trying to remove your potion status effects but failing to do so in a safe way and causing the crash.

Had a player on my server suffer a similar problem with an EnigmaticLegacy item, but fortunately it looks like they just released an update today to fix that problem with the Blazing Core.

---

Looking at Sinyc's crashlog that's something on the BloodMagic side of things trying to do something to a skeleton. Dunno if it'd be related though.
