### ISSUE TITLE
Force-Crash / Crashloop When changing mode on Integrated Dynamics Battery

### ISSUE THREAD

**Issue by ghost** [The-Nexus-Project/Limitless-3#119]
If you shift right-click while holding the Integrated Dynamics battery to charge the items in your inventory it immediately crashes the game, and will not allow you to reload it.

Looking for a solution outside of deleting the mod to hope the pack will load w/o it.

Recreated in a creative Super flat world, the exact same thing happened w/ fresh save.

**Comment by ghost** [comment]
Worth adding the crash persists even after replacing player.dat inventory files w. a backup.

**Comment by Gbergz** [comment]
Is this still the case in pack version 1.9.8?
