### ISSUE TITLE
No squids

### ISSUE THREAD

**Issue by InflamedSebi** [The-Nexus-Project/Limitless-3#12]
### Describe your issue, what happened?
There are no squids. Nowhere.
I repeatedly did '/kill @e[type=cod]' and got a single one to spawn after 15 minutes.
So probably the same issue like other packs. squids get blocked from spawning since all the other creatures (seahorse/cod) fill up the slots before squids can.

### Affected Version
1.5.0

**Comment by Gbergz** [comment]
fixed in 1.6.1
