### ISSUE TITLE
Items disappearing.

### ISSUE THREAD

**Issue by djekabsons** [The-Nexus-Project/Limitless-3#120]
OptiFine_1.16.5_HD_U_G6
OptiForge-MC1.16.5-0.5.0

(Problem was also present with older modpack and optifine versions)

At some seemingly random point, the item I am currently holding just disappears. If I had a jetpack in my "Back" slot the item would get replaced by the jetpack, as if it was being moved from Curios inventory to the hotbar. This has happened multiple times, most recently with a "Dank Storage" "Dank 7". For some reason it also simultaneously deleted my magnet, also in my hotbar.

The only idea I have is it might be related to my memory maxing out, something I can't really fix outside of just restarting the game every time I go exploring. (12200 MB allocated)

I really have no clue what causes this, but:
1. Wait an indeterminate amount of time. 
2. Have an item in your main or/and off hand.
3. Rightclick with the item in your hand, as if to use it. (Either using the item itself (ex. a bag), or to do something else (ex. opening a Crafting grid) with the item in main hand.
4. Both items, in the off hand and the main hand, disappear and your jetpack appears in place in the main hand. (If you have no jetpack equipped in the Curios "Back" slot, nothing appears in place, the item just disappears). 

[latest.log](https://github.com/The-Nexus-Project/Limitless-3/files/5905665/latest.log) 
The only thing i can notice in the log about the time it happened is "{name} moved wrongly" (128436th line [19:18:07]) but I am not sure if it's related.

- Pack Version: 1.9.3
- On a server?: No, Singleplayer.

**Comment by ghost** [comment]
I'm not sure how helpful it is, but I've experienced the exact same thing. Always the jetpack curio slot, to replace and delete the item in your hand. The only consistency I've noticed is it's typically when the game is already chugging. Logged plenty of hours hanging around my main area, no issues. Traveled and explored the nether and lost a dank null, and an enchanted bow to the jetpack swap issue.

**Comment by Gbergz** [comment]
Is this reproducable without optifine?

**Comment by djekabsons** [comment]
Yes, just recreated the bug in creative, i assume it also can happen in survival.

No optifine or optiforge, 
Modpack version 1.9.3

1. Open/Create a world
2. Fill the allocated memory (i did so by exploring, that is, generating lots of new chunks, both in overworld and nether)
3. Have a jetpack in the Curios "Back" slot
4. Right-click and close your inventory repeatedly with an item in hand (I used a "Dank 7")
5. Item disappears and jetpack appears in place. 

In the screenshot you can see a creative jetpack in slot 8, where before i had another Dank 7, next to the 2 in slots 6 and 7.

![2021-02-02_17 23 49](https://user-images.githubusercontent.com/78267848/106622529-5b79ef80-657c-11eb-923c-9c57c19b735c.png)

[latest.log](https://github.com/The-Nexus-Project/Limitless-3/files/5912233/latest.log)
Happened seconds before i took a screenshot (line 50010 [17:23:49])

**Comment by ghost** [comment]
Just lost a significantly full Silents Gem Bag to this same bug. Seems tied to large exploration/chunk generation. Gonna have to remember to relog between exploring and sorting.

**Comment by Royal99** [comment]
> Is this reproducable without optifine?

I don't have optifine and if installing it will get me other glitches i won't install optifine.
