### ISSUE TITLE
Ice Dragonsteel Axe is considered a pick and a sword

### ISSUE THREAD

**Issue by idvoid** [The-Nexus-Project/Limitless-3#121]
While enchanting this weapon, I can apply pickaxe enchants and some weapon enchants. It's tooltip shows it has a mining lv of 5 and mining speed of 10. When looking at stone it says it is not a pickaxe.
![2021-02-01_22 12 26](https://user-images.githubusercontent.com/28431463/106547495-4d27c700-64db-11eb-85ce-3431e0ea4d0e.png)

**Comment by Gbergz** [comment]
Well that's an axe? So it won't mine stone. "pickaxe enchantments" like efficiency etc is applicable to the axe.
