### ISSUE TITLE
Metallurgic Infuser recipe not showing in JEI

### ISSUE THREAD

**Issue by ghost** [The-Nexus-Project/Limitless-3#122]
The “JEI” is not showing the recipes for the Metallurgic Infuser ingot.

Example Steel Ingot, does not show the recipe on the Metallurgic Infuser (Mekanism) machine in the JEI mod

In game Page 1/2
![image](https://user-images.githubusercontent.com/54646457/106616025-d70f7880-654b-11eb-8da5-24f1179562dc.png)

In game Page 2/2
![image](https://user-images.githubusercontent.com/54646457/106616113-ed1d3900-654b-11eb-8c67-eafc99d633e6.png)

-------
As it should be shown in the JEI - Wiki Mekanism Steel Ingot - https://wiki.aidancbrady.com/wiki/Steel_Ingot

![Screenshot_1](https://user-images.githubusercontent.com/54646457/106615794-931c7380-654b-11eb-9249-59a1160e8f97.png)

**Comment by Gbergz** [comment]
It's there?
![image](https://user-images.githubusercontent.com/26634554/106806292-0ddab100-6668-11eb-9b14-d156a7115b14.png)
