### ISSUE TITLE
Fletching table not changing villager profession

### ISSUE THREAD

**Issue by Frankie4SD** [The-Nexus-Project/Limitless-3#124]
### Describe your issue, what happened?
villager does not become a fletcher

### To Reproduce
1. Place down fletching table
2. unemployed villager does not use the table

### Expected behavior
an unemployed villager should become a fletcher when next to a fletching table

### Affected Version
1.9.3

**Comment by Gbergz** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues/285
