### ISSUE TITLE
Game hangs then closes when trying to navigate the nether using mekanism jetpack

### ISSUE THREAD

**Issue by Nunbear** [The-Nexus-Project/Limitless-3#127]
### Describe your issue, what happened?
Game hangs then closes when trying to navigate the nether using mekanism jetpack

### To Reproduce

Did this twice trying to go through the nether

### Crash Reports & Logs (Don't paste entire crash reports here.)

https://pastebin.com/HHCq9eSg

### Affected Version

- Pack Version:  1.9.4
- On a server?: no was solo

**Comment by Gbergz** [comment]
Late reply, but might be easier to report this to mekanism instead.
Closing.
