### ISSUE TITLE
Items disappearing

### ISSUE THREAD

**Issue by Royal99** [The-Nexus-Project/Limitless-3#129]
### Describe your issue, what happened?
As you can see in the video linked below, i used Inventory Tweaks to put in the grid the items in my inventory and when i tried to take them back they disappeared, like if i was just modifying the recipe (idk if this is caused by InvTweaks or RFTools/both)

### To Reproduce
Use inventory Tweaks inside of a RFTools Crafter

### Screenshots
Imma put a video here to let you see with your own eyes
https://www.youtube.com/watch?v=StXN7ov7ygI 
### Affected Version
- Pack Version: 1.9.3
- On a server?: No, singleplayer

**Comment by Gbergz** [comment]
This issue is known and for now I can't seem to fix it.. Reported to Rftools dev & InventoryTweaks. No Dice. The blacklisting of the GUI doesnt work either.

**Comment by Royal99** [comment]
> This issue is known and for now I can't seem to fix it.. Reported to Rftools dev & InventoryTweaks. No Dice. The blacklisting of the GUI doesnt work either.

Sorry for posting then, stupidly i didn't check if other people had already reported it, i look forward for a fix soon, thanks anyway for the response.

**Comment by Gbergz** [comment]
No worries, hopefully it'll be fixed.
