### ISSUE TITLE
Too Many Fish!

### ISSUE THREAD

**Issue by sldains** [The-Nexus-Project/Limitless-3#13]
We just downloaded the latest update, 1.6.1, with a LAN server. Whatever you did to fix the squid spawning issue must have overclocked the rest of the fish because the river by our base is now so choked full of fish the game is nearly unplayable it's so laggy. The river is basically solid fish. 

![2020-10-22_16 21 35](https://user-images.githubusercontent.com/72796241/96925889-d8c49d00-1482-11eb-828f-bb58e8918c06.png)

**Comment by Gbergz** [comment]
The squid fix is a fix in the mod Aquaculture, whatever fix they did must've messed with other spawnrates.

**Comment by Gbergz** [comment]
https://github.com/TeamMetallurgy/Aquaculture/issues/149
