### ISSUE TITLE
Some Create Ores Not Washing

### ISSUE THREAD

**Issue by Meek97** [The-Nexus-Project/Limitless-3#130]
There are a few crushed ores in the mod pack that disappear instead of turning into nuggets when trying to use the Create ore washing mechanic. I haven't done enough testing myself yet to determine if this is specifically an issue with the mod pack (perhaps some custom recipe issue) or an issue with the Create mod. But only aluminum quick silver and tin fail to turn into nuggets:
![image](https://user-images.githubusercontent.com/14891222/107872298-633c6c80-6e77-11eb-9298-1d233c2b3357.png)

![CreateBug](https://user-images.githubusercontent.com/14891222/107872313-73544c00-6e77-11eb-963a-92de0529a683.gif)

**Comment by Meek97** [comment]
so - I don't think that this is an issue with the Create mod directly. Popping into a test pack with only Create, the Thermal series mods, and JEI - it is able to ore wash all of the available ores in that pack, tin included (it wouldn't wash aluminum or quicksilver, but that's because those ores are not in this test pack)

**Comment by Gbergz** [comment]
Trying to get this fixed for next update.

**Comment by Gbergz** [comment]
Though Quick Silver doesn't exist in Limitless 3.
And in my indev instance, aluminum & tin do wash.
Edit: False, in JEI they do wash. Not actually in-game.

**Comment by Gbergz** [comment]
Alright, it's fixed for next update!

**Comment by Meek97** [comment]
Fixed in 1.9.5 release
