### ISSUE TITLE
It's not possible to level up farmers

### ISSUE THREAD

**Issue by Khris777** [The-Nexus-Project/Limitless-3#131]
I'm not sure if this is an issue of Thermal or of this modpack, so I think I'll start here.

Novice farmers seem to only have trades where you give them vegetables from the Thermal Series and they give you emeralds. I haven't found a single farmer that had trades that weren't like that. However to grow these vegetables you need the seeds first and you only get those from level 2 farmers (according to JEI and my explorations so far). So you'd have to level up a farmer to level 2 to get the stuff you need to level them up to level 2. So you can't level up farmers at all right now.

### Affected Version
- Pack Version: 1.9.4
- On a server?: No

**Comment by Gbergz** [comment]
It's possible to level them up but it is indeed an issue that Thermal's seeds are the majority of the trades.

Here's a carrot trade.
![image](https://user-images.githubusercontent.com/26634554/109181394-284a0b00-778c-11eb-9c16-d972a2fdbc17.png)

So it's an issue but not game breaking.

**Comment by Gbergz** [comment]
Found a comment on the matter here.
https://www.reddit.com/r/feedthebeast/comments/kgqid0/116_thermal_series_crops/

Closing this as it looks like its intended.
