### ISSUE TITLE
My game crashes upon trying to load a savefile

### ISSUE THREAD

**Issue by Miladmore** [The-Nexus-Project/Limitless-3#133]
### Describe your issue, what happened?
My game Crashes when i want to create or load a world

### To Reproduce
1. Run the game
2. Select single player
3. Load any of my savegames

### Expected behavior
My game runs i guess 

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://paste.ee/p/SO01j

### Affected Version
1.16.5
- Pack Version: 1.9.5
- On a server?: No

**Comment by Gbergz** [comment]
By the looks of your crash-report, you have the Forge version **36.0.42** while the pack uses **36.0.25**, which could explain why you're having issues. You also have the mods **TheAbyss2**, **Structurize** & **Relics**, which TNP Limitless 3 does not have.. I would suggest NOT modifying the modpack and then reporting stuff as not working..
