### ISSUE TITLE
Reduced Enderman spawn in the end?

### ISSUE THREAD

**Issue by Kangy1103** [The-Nexus-Project/Limitless-3#134]
### Describe your issue, what happened?
I'm making a enderman XP farm in the end but it seems the enderman aren't spawning in numbers.
I've built this before so I know the design works. Have the spawn rates been reduced?

### To Reproduce

1. Build enderman xp farm
2. Wait for enderman to spawn
3. See not many spawn
4. Don't profit

### Affected Version

- Pack Version: 1.9.5
- On a server?: Yes

**Comment by Gbergz** [comment]
They're spawning like normal, but at reduced rates to reduce lag.

**Comment by Gbergz** [comment]
Just wait and they'll spawn.

**Comment by Kangy1103** [comment]
Gotcha, just wanted to make sure I wasn't going crazy, thank you :)

**Comment by Gbergz** [comment]
If you want normal spawn rates you can go into ``performant-common.toml`` and change this line.

	#Entity spawn interval setting, determines how frequently entities are spawned overall. 1 = Vanilla default, default = 10
	#Range: 1 ~ 1000
	spawnInterval = 10
	
	from 10 to 1.

**Comment by Kangy1103** [comment]
Great, thank you!
