### ISSUE TITLE
Villager Breeding/Farming Impossible

### ISSUE THREAD

**Issue by Cronje99** [The-Nexus-Project/Limitless-3#135]
After a frustrating two hours of throwing carrots at a pair of villagers and them not breeding, I realized that, with the default gamerules in place, making villagers breed was impossible. Please enable mobGriefing by default, since that is what allows villagers to work farmland and pick up food to breed.

**Comment by Gbergz** [comment]
Mobgriefing gamerule is enabled by default. Nothing has changed.

**Comment by Gbergz** [comment]
![image](https://user-images.githubusercontent.com/26634554/109180685-6d217200-778b-11eb-9a74-cbae10f28d22.png)
