### ISSUE TITLE
Client mods in server pack

### ISSUE THREAD

**Issue by Dryelo** [The-Nexus-Project/Limitless-3#136]
There are two client-only mods in the server files:

konkrete_1.1.3_MC_1.16.2-1.16.5.jar
MouseTweaks-2.14-mc1.16.2.jar

I don't think they create an issue but they should be removed.

Great modpack, thanks for all your efforts!  👍

**Comment by Gbergz** [comment]
Got that solved for next update. Thanks for report 👍
