### ISSUE TITLE
When I go in the server it says an error.

### ISSUE THREAD

**Issue by GamerLoganDean** [The-Nexus-Project/Limitless-3#137]
It looks really weird it looks like a mod, dimension or item could've done it.

I expected to go on the server and play!

![image](https://user-images.githubusercontent.com/79916667/109652588-e3d9b900-7b57-11eb-8c1b-ab2217bf4e77.png)

1.16.5
The main Limitless 3 server.

**Comment by Gbergz** [comment]
Chat about this issue in #support instead in our discord server.
https://discord.gg/gwzpyQb
