### ISSUE TITLE
Crash on World load

### ISSUE THREAD

**Issue by FailPail** [The-Nexus-Project/Limitless-3#139]
Getting Illeagal StateException: lock is no longer valid, and a NullPointerException: player ticking on world load. the issue happened a few days after I started playing on a new world.

I don't know how to reliably reproduce it as it happened a few days after starting the world and then it crashes during gameplay and I can't load in anymore. The thing I was doing right before it crashed was mining a 3x3 with the mining gadget

1. start a new world
2. wait for an unknown amount of time
3. game crashes and world no longer loads.

lock is no longer valid log
[crash-2021-03-03_18.48.48-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/6086576/crash-2021-03-03_18.48.48-client.txt)

player ticking log
[crash-2021-03-03_19.15.39-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/6086577/crash-2021-03-03_19.15.39-server.txt)

Version 1.9.6
singleplayer world

**Comment by Gbergz** [comment]
Looks like a Cyclic crash, check if its been reported if it hasnt report it here: https://github.com/Lothrazar/Cyclic/issues
``
java.lang.NullPointerException: Ticking player
	at com.lothrazar.cyclic.item.storagebag.StorageBagItem.lambda$bagHasItem$1(StorageBagItem.java:252) ~[cyclic:1.16.5-1.1.8]``

Also try a different launcher if you're using CurseForge.

These
- GD Launcher: https://gdevs.io/#downloadContainer
- MultiMC: https://multimc.org/#Download

**Comment by FailPail** [comment]
So using multiMC did not let me load into the world, however there is a an issue regarding the storage bag in cyclic that results in the same errors. there is already a pull request that fixes it. do you have an ETA on when the pack will be updated after cyclic is updated?

**Comment by Gbergz** [comment]
No eta, you could update it manually.

**Comment by FailPail** [comment]
Could you detail or point me in the right direction on how to do that?

**Comment by Gbergz** [comment]
Just download the latest file from their modpage. https://www.curseforge.com/minecraft/mc-mods/cyclic (When its released.)

Then head into the modpacks rootfolder, depending on the launcher you have.
Remove the cyclic jar from there then replace it with the new downloaded one.

**Comment by FailPail** [comment]
awesome, though since the fixes are present as a pull request is it possible to manually replace the affected files? I just want to play as soon as possible.

**Comment by Gbergz** [comment]
No idea, best to wait until it's released.
