### ISSUE TITLE
Degraded performance in v1.6.1

### ISSUE THREAD

**Issue by kevinrpb** [The-Nexus-Project/Limitless-3#14]
### Describe your issue, what happened?

After updating to v1.6.1 the performance of the pack is severely affected. Going form 20 TPS to around 9 TPS, which makes the game go from ~70 fps to ~15 fps. ☹

### Affected Version

- Pack Version: 1.6.1

**Comment by Gbergz** [comment]
This is probably related to this issue: https://github.com/The-Nexus-Project/Limitless-3/issues/13

**Comment by kevinrpb** [comment]
Aww =/ fishy situation we got here.

Since I was not in a place with water around, I didn't think it was the same issue, but I think it is. I'll close this, then! Thanks for the quick reply!
