### ISSUE TITLE
Allow Thermal And Silents oil to be processed in pneumaticrafts refinery

### ISSUE THREAD

**Issue by tyler489** [The-Nexus-Project/Limitless-3#140]
### Describe your issue, what happened?
Thermal and silent mekanisms oil cannot be processed in the pnemuaticraft refinery, however Ie's and pneumaticrafts oil will work

### To Reproduce
attempt to put thermal or silent mekanism oil into a refinery.

### Expected behavior
It to process the oil
### Affected Version
- Pack Version: 1.9.5 i believe 
- On a server?: yes

**Comment by Gbergz** [comment]
This is probably something to report to the mod author instead.

**Comment by tyler489** [comment]
I feel like this is a pack issue as they allow all oil that uses Forge:crude_oil and not sure what silent uses. they  provide ways for pack devs to add recipes via https://github.com/TeamPneumatic/pnc-repressurized/wiki/Recipes-1.14.4-and-1.15.2-1.16.x#refinery

https://github.com/TeamPneumatic/pnc-repressurized/issues/756q

**Comment by tyler489** [comment]
To clarify the oil cannot be put in the refinery and that is why it won't process

**Comment by desht** [comment]
(PNC:R mod author here)

I agree with @tyler489 - cross-mod integration like this should be done at the modpack level.  Adding a fluid to the `forge:crude_oil` tag is sufficient to get it accepted by the PNC:R Refinery, so easy enough to do.

Note: Silent's uses `forge:oil` although they used to use `forge:crude_oil`, and Thermal doesn't add its oil to a fluid tag at all).

**Comment by Gbergz** [comment]
Will look into adding this then. Thanks for the replies.

**Comment by Gbergz** [comment]
Alright added support for both for next update (v1.9.7).
![image](https://user-images.githubusercontent.com/26634554/111038370-cd214500-8428-11eb-835e-bc6b0e5e2b3c.png)
