### ISSUE TITLE
Issue updating server files from 1.9.5 to 1.9.6

### ISSUE THREAD

**Issue by Wargresh** [The-Nexus-Project/Limitless-3#141]
I was able to download the 1.9.6. files and then run the batch file to pull all the configs and mods down.  I uploaded everything except for the world config to my hosted server and now whenever anyone tries to connect it displays "Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Recursive load of: INVALID-tetra:modular_sword".

**Comment by Gbergz** [comment]
You can update the mod Tetra manually and it should be fixed.
This is done for next pack update however.
