### ISSUE TITLE
Caving Torch Charm from Cyclic closes world.

### ISSUE THREAD

**Issue by MdBourg98** [The-Nexus-Project/Limitless-3#143]
Did report to mod author, Item performs correctly with just Cyclic.

### Describe your issue, what happened?
Received Cyclic, Caving Torch Charm form loot bag. World closed itself, Client did not crash.

### To Reproduce
Have "Caving Torch Charm" from "Cyclic" in inventory

### Crash Reports & Logs (Don't paste entire crash reports here.)
No Report Generated

### Affected Version
Version 1.9.7
NOT on server

**Comment by Gbergz** [comment]
Hello.
I can't reproduce this issue. Caving Charm works perfectly fine.

**Comment by Gbergz** [comment]
Maybe it's due to the fact it was received from a loot bag. I'll blacklist it for future updates.

In the meantime you can use a nbt editor and remove it from your inventory.
