### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by Zcey1** [The-Nexus-Project/Limitless-3#145]
There is a problem with Upgraded Aquatic that prevents launching the game on the latest version. Attached is the crash report.
[crash-2021-03-16_13.05.05-fml.txt](https://github.com/The-Nexus-Project/Limitless-3/files/6151947/crash-2021-03-16_13.05.05-fml.txt)

**Comment by Gbergz** [comment]
Mod loading errors usually goes away after restarting the game a few times.
