### ISSUE TITLE
Item Recipe Conflict

### ISSUE THREAD

**Issue by blockbreaker1361** [The-Nexus-Project/Limitless-3#146]
https://imgur.com/a/Hy9Dedi
There is a recipe conflict between the Minecraft chain and the chain from Forbidden and Arcanus.

**Comment by blockbreaker1361** [comment]
Forget about this. I didn't realize their was an option to bypass conflicts. Sorry.

**Comment by Gbergz** [comment]
That's fine. Thanks for report. I'll fix it for next update. 👍
