### ISSUE TITLE
End freeze

### ISSUE THREAD

**Issue by Ryuuzzik** [The-Nexus-Project/Limitless-3#147]
### Describe your issue, what happened?
When fighting the ender dragon, the world just freezes (no tick updates), "waiting for server" message. I can move, break blocks, but no item drops, no mob movement. Tried to move onto a dedicated server, the same happens, but the server will restart after 3 minutes because a tick took more than 180s (watcher).  No crashlogs. Would really love to play, but with this it is unplayble. (sometimes it happened in the overworld, but in the end it is 100% to happen for me)
No optifine, no other mods.

### To Reproduce
For me... 
1. fight dragon
2. freeze

### Expected behavior
No freezes? -_-

### Crash Reports & Logs (Don't paste entire crash reports here.)
no crash log

### Affected Version
- Pack Version: 1.9.7
- On a server?: no

**Comment by Gbergz** [comment]
Are you perhaps using a bow with any of the following enchantments: (Homing, True Shot.) ?

**Comment by Ryuuzzik** [comment]
Actually yes, I am using true shot.

**Comment by Gbergz** [comment]
That's why then. It freezes the server for some unknown reason.

**Comment by Gbergz** [comment]
Confirmed then, closing.
