### ISSUE TITLE
Fps drop.

### ISSUE THREAD

**Issue by stels9fox** [The-Nexus-Project/Limitless-3#149]
After upgrading from 1.9.6 to 1.9.8b
In version 1.9.6, I often used the mystic staff of explosive mana condensation but with the update to 1.9.8b.
When using the mystic staff of condensation of explosive mana or the scroll of Rho ​​Aias from Mahou Tsukai, the fps drops to 1 and there is ~ 200 ms per tick
Also, a drop in FPS from 50 to 10 occurs when using the Gandr scroll. (Scroll Gandr used to squander FPS)
However, the Mahoujin Projector does not affect the FPS.
Items from botany that also very much squander FPS: shard of Laputa(during operation, a ray of mana is created for each raised block), a flugel tiara (When jerking. Most likely due to chunks being progressed).
Setting the number of particles does not affect the lags or has little effect.
These are just the items that I have checked, possibly others that create a lot of moving particles can lead to lags.
Upd: If you remove entityculling-1.1.0 then fps does not drop when using mystic staff of explosive mana condensation
![01](https://user-images.githubusercontent.com/81447418/112701583-14d0b380-8ea2-11eb-901c-3dcc7a789486.jpg)

**Comment by Gbergz** [comment]
Report issue to Entity Culling since it seems to be related. 

https://github.com/tr7zw/EntityCulling-Fabric/issues

**Comment by stels9fox** [comment]
I sent a report about this situation to the author of the mod, but in any case, I had to tell the author of the modpack about the dubious mod, so that he decided whether he needed it in the modpack or not.

**Comment by stepsword** [comment]
I can't really comment on the explosion issue or Rho Aias, as I don't know what would cause that, but for Gandr, you can set NO_SHADERS=true in client config and it'll probably remove most of the FPS drop.

**Comment by stels9fox** [comment]
The author of the Entity Culling mod has updated the mod and now there is no performance issue. Please remember to update the mod in the next update.

**Comment by Gbergz** [comment]
Next update will have the latest update. Always. 👍
