### ISSUE TITLE
Mob Masher killing Vindicator causes server crash

### ISSUE THREAD

**Issue by Mnky313** [The-Nexus-Project/Limitless-3#150]
We have a mob grinder using a mob masher and once a vindicator is killed the server crashes.
rejoining the server causes it to crash again. Had to revert to a backup before the spawner was running

[crash-2021-03-28_01.11.05-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/6216895/crash-2021-03-28_01.11.05-server.txt)

**Comment by Gbergz** [comment]
https://github.com/vadis365/Mob-Grinding-Utils/issues
