### ISSUE TITLE
Opening the Chisels & Bits radial menu crashes the game

### ISSUE THREAD

**Issue by Chocobro** [The-Nexus-Project/Limitless-3#151]
### Describe your issue, what happened?
When opening the Chisels & Bits radial menu, the game crashes, booting you to the main menu.

### To Reproduce
1. Get a Chisels & Bits chisel (tested with both Iron and Diamond chisels)
2. Try to open the radial menu with Left Alt
3. Crash

### Expected behavior
The radial menu should appear.

### Crash Reports & Logs (Don't paste entire crash reports here.)
[Crash Report](https://pastebin.com/MLJyqJqh)

### Affected Version
- Pack Version: The pack version is TNP Limitless 3 - 1.16.5. The jar is `Limitless-3-1.9.7.zip`.
- On a server?: Yes and no. Tested on a server and on a singleplayer world, where the bug is reproducible on both.

### Additional:
I tested if the crash was reproducible by binding the radial menu key to right alt (ALTGR) instead, and the crash still happens, so I don't think a keybinding conflict is what's causing this.

**Comment by Gbergz** [comment]
Fixed in 1.9.8
