### ISSUE TITLE
Mahou tsukai projection duplication + Fix

### ISSUE THREAD

**Issue by wakkytabbaky** [The-Nexus-Project/Limitless-3#152]
### Describe your issue, what happened?
using mahou tsukai's projection spell ( summons a limited durability copy of the item it memorizes) on anything with the indestructible enchant ( forbidden & arcanus mod) on it will dupe it permanently ( not intended)

### To Reproduce

1. make a mahou tsukai projection spell
2. memorise any tool / weapon with indestructible on it 
3. use spell
4. voila, new indestructible duped item

### Expected behavior
the spell is only supposed to summon the memorised item with limited durability.

### Fix
this is from the mahou tsukai mod dev himself 

stepcros
I think there's a projection enchant blacklist "PROJECTION_ENCHANTMENT_BLACKLIST" in the server config that you can use to prevent this. you'd add "modname:indestructible" or whatever its official name is to that list.

So like 
PROJECTION_ENCHANTMENT_BLACKLIST = ["modname:indestructible"]

If I remember right, I think this config was created specifically for that enchant actually lol. But its up to the modpack dev to do it.

**for you guys on the tnp pack author side just need to add this into the modpacks config so its blacklisted by default**

### Affected Version
- Pack Version: 1.9.7
- On a server?: private server, no changes in the pack at all

**Comment by Gbergz** [comment]
Thanks for the report. Fixed for 1.9.9!
