### ISSUE TITLE
More of a suggestion for a mod, rather than a mod suggestion

### ISSUE THREAD

**Issue by EveTFB** [The-Nexus-Project/Limitless-3#153]
how many sheep do we have to sacrifice for sea serpents from ice and fire to either be turned way down or confined to deep ocean biomes, spawn wise?

these things do way too much damage, and move too much for how much they spawn, they make the ocean borderline unplayable for newer people, and by the time you get strong enough to fight multiple of these, you wont need anything from the ocean anyways

**Comment by Gbergz** [comment]
Fixed for 1.9.9, they'll only spawn in the Deep Ocean biomes.
