### ISSUE TITLE
Crashing when launching modpack

### ISSUE THREAD

**Issue by tsalkenov** [The-Nexus-Project/Limitless-3#154]
When I launch modpack it starts to load then after a couple seconds it crashes 
[crash-2021-04-01_12.11.32-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/6241382/crash-2021-04-01_12.11.32-client.txt)

**Comment by tsalkenov** [comment]
Sorry if I did something wrong first time on Github

**Comment by Gbergz** [comment]
Updating to a new update from a previous can have issues. Also your forge is 36.1.3 when the pack is on 36.1.2, you also have curious jetpacks which was removed recently.

Try a complete re-install of the modpack.
