### ISSUE TITLE
Scannable Issue

### ISSUE THREAD

**Issue by DisgameWiz** [The-Nexus-Project/Limitless-3#155]
### Describe your issue, what happened?
I was using the "Scannable" scanner with the range upgrade, mob upgrade, and item upgrade which was looking for chests. My scanner finished charging and found the chest but before I would get to it my game crashed. I tried rejoining but it kept crashing.

### To Reproduce
Not exactly sure of how but using "Scannable" scanner and then mining too quickly???

### Expected behavior
The scanner has worked for me before in looking for chests but this specific time it crashed my game. It would just find the chest for me and I would go to it.

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/7DrjjY4g

### Affected Version
- Pack Version: Limitless-3-1.9.8
- On a server?: Yes, The Official One

**Comment by Gbergz** [comment]
https://github.com/MightyPirates/Scannable/issues
