### ISSUE TITLE
Shears -  Cutting/digging with efficiancy like effects

### ISSUE THREAD

**Issue by Tsorii** [The-Nexus-Project/Limitless-3#157]
V 1.9.8b

Normal shears (and others added by mods) cut trees and mine with incredible speed.

Wont allow you to pickup ores mined with them so still being recognised as shears, but is still incredibly quicker than using an axe or pickaxe for wood, trees or stone.

**Comment by Gbergz** [comment]
Thanks for the report but not sure how I should fix that.
