### ISSUE TITLE
Hi I have a prob

### ISSUE THREAD

**Issue by DuskyFall** [The-Nexus-Project/Limitless-3#158]
I was trying to download the new update but it didn't let me, so I deleted the older version, and then I couldn't download the mod pack at all either the older version or the new one. So if there is a way to fix it please tell me and the others if they have the same problem, thank you for reading <3

**Comment by monkeychex3** [comment]
@DuskyFall are you trying to download manually or through Curseforge? Sometimes having "allow content management for this profile" box checked will prevent the "version" dropdown from being reachable.

**Comment by DuskyFall** [comment]
I was trying to download it from curseforge

**Comment by DuskyFall** [comment]
So how do I disable it?

**Comment by monkeychex3** [comment]
open the profile of TNP3 in Curseforge (in My Modpacks), click the vertical "..." to the left of "play" and the download button. In that menu, click "profile options", then make sure NO CHECK is in the box "Allow content management for this profile"

**Comment by DuskyFall** [comment]
I do not have the mod pack I deleted it but it does not allow me to download it again and don't know why, and whenever I try it says" Object reference not set to an instance of an object"

**Comment by monkeychex3** [comment]
I believe this is an issue on the curseforge side, but I am out of my expertise here. Other things I've read from other packs when I googled that error message make it appear like the problem resolved itself, or the users installed a previous version and then update to the current to fix. Let's hope someone more qualified comes!

**Comment by DuskyFall** [comment]
thank you for your help and time <3
