### ISSUE TITLE
Everythings green!

### ISSUE THREAD

**Issue by smartgamer15** [The-Nexus-Project/Limitless-3#159]
### Describe your issue, what happened?
every icon has turned green, even in JEI and items like chests have a green tint

### To Reproduce
not sure how to reproduce it it happens when i log in

### Expected behavior
not green icons

### Screenshots
https://user-images.githubusercontent.com/81994098/113623680-b091ba80-962c-11eb-9034-ddb6c1530497.png

### Crash Reports & Logs (Don't paste entire crash reports here.)
not crashing

### Affected Version
1.9.9B
- Pack Version: 
- On a server?: no

**Comment by Gbergz** [comment]
https://github.com/Mithion/Mana-And-Artifice/issues/206
