### ISSUE TITLE
Tinkers smeltery is broken

### ISSUE THREAD

**Issue by Arkytact** [The-Nexus-Project/Limitless-3#160]
### Describe your issue, what happened?
When trying to create an alloy such as brass or bronze in a 5x5x5 internal tinkers construct smeltery it creates said alloy within as a liquid. However when extracted using a drain, faucet and casting basin or table the result is always gold ingots or copper blocks.

### To Reproduce
- Build a tinkers smeltery with internal dimension of 5x5x5, added 2 drains and some gauges.
- Add nescessary blocks or ores.
- Extract using the drain into a basin or table with ingot mold.

### Expected behavior
Result is always a gold ingot or a copper block

### Crash Reports & Logs (Don't paste entire crash reports here.)
Does not result in a crash.

### Affected Version
- Pack Version:  1.9.9b
- On a server?: no

**Comment by Gbergz** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/4283

Go into the Performant config and disable Cache Recipes

**Comment by Gbergz** [comment]
Config is changed by default next update.
