### ISSUE TITLE
Performant cause crash when opening Pattern Terminal

### ISSUE THREAD

**Issue by ProOrange** [The-Nexus-Project/Limitless-3#161]
### Describe your issue, what happened?

Sometimes openning Pattern Terminal from AE2 lead to game crash, but not always, sometimes it's just laggy. 
I had discussion with AE2 devs and it turns out that this lags caused by Performant.  After removing Performant from modpack things became stable.

### To Reproduce

1. Setup base AE2 network with 6-10 filled with items storage cells
2. Place Pattern Terminal
3. Fill player inventory with different items
4. Open pattern terminal
5. Sometimes app will crash, sometimes just lag for 3-30 seconds

### Expected behavior

Pattern terminal should open with lesser lags (without performant it took aroung 2 seconds always, without any exceptions)

### Affected Version

- Pack Version: 1.9.9b
- On a server?: Yes, but server isn't affected

**Comment by Gbergz** [comment]
Hey, you know if this is still happening? Tried to replicate, no success

**Comment by DrPinguin98** [comment]
hey,

the problem exists in **AE2 version 8.3.1**. I also play in the **Modpack Version 1.10.3**. The ME system is still pretty basic at the moment, but connected is 1 ME bus to a Quantum Storage Controller, a Diskdrive, a Crafting Terminal and just the Pettern Terminal.

After joining the server you can access the terminal without any problems, but the longer you are on the server the stronger the lags become, up to the point when you open the terminal after about 10 minutes, the game simply freezes, but the sound keeps playing, so to speak, it hangs in a not displayed GUI.

Looking at AE2's github, it seems that the problem only appears here in our modpack.  [https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5043](url)

**Comment by Gbergz** [comment]
Looks to be a performant issue, yes. Remove the mod if you want. Closing
