### ISSUE TITLE
Error when I try to install the modpack on the 1.16.5 minecraft version

### ISSUE THREAD

**Issue by Skrspy** [The-Nexus-Project/Limitless-3#162]
### Describe your issue, what happened?
When I try to install it it doesn't work, it gives me a file error

### To Reproduce
1. Go to 'modpack home page'
2. Click on 'install'
3. Wait....

### Screenshots
![Screenshot_1](https://user-images.githubusercontent.com/82089261/113845507-439e3200-979e-11eb-8b9a-a143a3a634d6.png)

### Affected Version

- Pack Version: 1.16.5
- On a server?: no

**Comment by Gbergz** [comment]
CurseForge Launcher just loves having issues. Try one of these.
**- GD Launcher:** https://gdevs.io/#downloadContainer
**- MultiMC:** https://multimc.org/#Download
