### ISSUE TITLE
CRASHING !!!

### ISSUE THREAD

**Issue by OveR1337XD** [The-Nexus-Project/Limitless-3#163]
**I Just downloaded mod and its crashes here is log and screenshot.**

![Screenshot 2021-04-12 004817](https://user-images.githubusercontent.com/3746977/114324141-d9341b80-9b28-11eb-9793-426164aab262.png)
[crash-2021-04-12_00.46.18-fml.txt](https://github.com/The-Nexus-Project/Limitless-3/files/6292918/crash-2021-04-12_00.46.18-fml.txt)

**Comment by Gbergz** [comment]
What launcher. CurseForge?

**Comment by OveR1337XD** [comment]
GD Launcher

**Comment by Gbergz** [comment]
Alright, I would try to restart. Those errors could happen. If that doesn't work try completely reinstalling the pack.

**Comment by ghost** [comment]
my modpack happens and i just restart the modpack, sometimes it can be the java ... i'm using the java 15 and java 8.

**Comment by OveR1337XD** [comment]
Fixed by changing Java version! I was using the wrong version in GD Launcher. I fixed it by choosing an automatic java setup in GD Launcher and that fixed for me! You can close this now!
