### ISSUE TITLE
Motorboats can drop from Loot bags but these are broken.

### ISSUE THREAD

**Issue by shinji257** [The-Nexus-Project/Limitless-3#164]
### Describe your issue, what happened?
Motorboats from Immersive Petroleum currently drop from Loot bags

### To Reproduce
Lootbag drop issue

### Expected behavior
These probably should be blacklisted as the tooltip on it has indicated it is broken and it isn't even visible or craftable in JEI at all.

### Screenshots
![image](https://user-images.githubusercontent.com/261005/114587259-7c814f80-9c53-11eb-8880-70280ba4b3bf.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
No crash logs or reports as it isn't a crash

### Affected Version

- Pack Version: 1.9.9a
- On a server?: Yes

**Comment by Gbergz** [comment]
thanks for the report, i'll blacklist for next update!
