### ISSUE TITLE
Silent Gear "Custom Gem" blank is dropped from loot bags.

### ISSUE THREAD

**Issue by shinji257** [The-Nexus-Project/Limitless-3#165]
### Describe your issue, what happened?
A blank (and probably invalid) custom gem drops from Silent Gear via the Loot Bags.  I did check the config and looks like you blacklisted other items but didn't get this one.

### To Reproduce

Lootbag drop issue

### Expected behavior
Probably shouldn't drop as it looks like it should be created via a different method.

### Screenshots
![image](https://user-images.githubusercontent.com/261005/114651859-bafa2700-9cb2-11eb-9f36-3917e1ab08ff.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
Not a crash

### Affected Version

- Pack Version: 1.9.9b
- On a server?: Yes

**Comment by Gbergz** [comment]
Thanks for the report. Added to the blacklist. 👍
