### ISSUE TITLE
Quest "Insanium Leggings" is duplicated

### ISSUE THREAD

**Issue by shinji257** [The-Nexus-Project/Limitless-3#166]
### Describe your issue, what happened?
The Insanium Leggings quest is duplicated and replaces the one for the chestplate in the quest tree

### To Reproduce

Look at the quest tree and where there should be a quest for Insanium Chestplate is one for the Leggings instead.  There is a second one in the correct location.

### Expected behavior
There should be an Insanium Chestplate quest

### Screenshots
![image](https://user-images.githubusercontent.com/261005/114652991-0ca3b100-9cb5-11eb-84be-27a765c859ce.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
Not a crash.  Quest tree issue.

### Affected Version

- Pack Version: 1.9.9b
- On a server?: Yes

I apologize if this was fixed in 1.10.0a and I have not actually checked it there.  There was no mention about quest fixes in the changelog.

**Comment by Gbergz** [comment]
Hey, thats strange.

I've gone ahead and fixed this for the next update!

Thanks for the report,
**-** Gbergz
