### ISSUE TITLE
Iron Furnace "Upgrades" related to materials not enabled are dropped from loot bags

### ISSUE THREAD

**Issue by shinji257** [The-Nexus-Project/Limitless-3#167]
### Describe your issue, what happened?
It is possible to get Iron Furnaces upgrades for materials not in this pack.  In this case I got an AllTheModium to Vibranium upgrade which (as far as I can tell) isn't enabled in the pack and unobtainable.  

### To Reproduce
Loot bag drop issue

### Expected behavior
This item likely shouldn't drop.  I suspect there are others with Iron Furnaces but don't have their IDs so I guess they would get blacklisted as we get them.  I did notice in the config you had already blacklisted some other ones and the Vibranium furnace.

### Screenshots
![image](https://user-images.githubusercontent.com/261005/114653802-d7985e00-9cb6-11eb-8a7a-26024522696d.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
Not a crash, Loot bag issue.

### Affected Version

- Pack Version: 1.9.9b
- On a server?: Yes

**Comment by Gbergz** [comment]
Thanks for the report. Added to the blacklist. 👍
