### ISSUE TITLE
Stradpoles not working in the nether and crashing my server.

### ISSUE THREAD

**Issue by Mbimajosh** [The-Nexus-Project/Limitless-3#168]
Alex's mobs stradpoles cause crashes in the never in the latest version of tnp i have disabled them myself personally in the config as i haven't seen any nor do i know what they do. I'm happy with this and will continue to play my version of it as i don't want to update for a fix cause world will break but i just thought it would be good to tell you,

**Comment by Gbergz** [comment]
Thanks for telling me. But you should probably report that to Alexs Mobs.

**Comment by Mbimajosh** [comment]
Your modpack is fire though best one I've played in a while, I reckon it'd
be cool to have doggy talents since it has such an animals are now useful
vibe but I'm staying on the older version anyway cause my world might get
broken otherwise.

**Comment by Gbergz** [comment]
This is supposedly fixed in the new Alex's Mobs update
``-Fixed crash with Straddler and Stradpole``

Which will be included in the next pack update.

**Comment by Mbimajosh** [comment]
If I update can my world also be updated okay? For a server?

**Comment by Gbergz** [comment]
You can update the mod manually yes.

**Comment by Mbimajosh** [comment]
Do you know how i would do this?
