### ISSUE TITLE
Lifesteal from Ma Enchants breaks drop rates

### ISSUE THREAD

**Issue by Xetaxheb** [The-Nexus-Project/Limitless-3#169]
### Describe your issue, what happened?
If you enchant a weapon (in my case silents gear swords; including a basic converted diamond sword) with Ma Enchants: Lifesteal it breaks all reliquary drops and seems to nerf looting a bit and scavenger output to 0, with who knows what else. 

### To Reproduce
1. Get a slime spawner and looting sword (scavenger for bonus points)
2. Kill slimes, see you get slime pearls
3. Add a Ma Enchants Lifesteal book to sword
4. No more pearls

### Expected behavior
Pearls

### Affected Version

- Pack Version: Limitless 3 - v1.9.9b I believe. Ma-Enchants 1.116.3-3.5.0.
- On a server?: Singleplayer.

Opened issue with mod author here but might want to disable it since there's other life steal enchants anyway. https://github.com/Maciej916/Ma-Enchants/issues/28

**Comment by Gbergz** [comment]
Thanks for the report. Disabled for v1.10.3 (next update).
