### ISSUE TITLE
Client crash when inserting a weapon or tool that has Enigmatic Legacy lore applied into an anvil

### ISSUE THREAD

**Issue by shinji257** [The-Nexus-Project/Limitless-3#170]
### Describe your issue, what happened?
Game client crashes when adding weapons or tools with a Enigmatic Legacy lore lines applied

### To Reproduce

1. Craft (or acquire) a Lore Fragment and Architect's Inkwell if needed
2. Set new lore on the Lore Fragment using the Architect's Inkwell
3. Apply new Lore Fragment to a weapon or tool of choice using an anvil and remove it.
4. Move the same weapon or tool back to the anvil and it will likely crash at this point

### Expected behavior
It shouldn't crash upon inserting the weapon or tool in the anvil at step 4.

### Crash Reports & Logs (Don't paste entire crash reports here.)
 

https://pastebin.com/vTRuhZYP

### Affected Version

- Pack Version: 1.10.0a
- On a server?: Yes

**Comment by Gbergz** [comment]
Late reply but,
Is this still happening? Not sure if its anything I can fix on my side unfortunately. Try reporting it to the mod author.
