### ISSUE TITLE
Ore Excav seems broken

### ISSUE THREAD

**Issue by OuroborosRahu** [The-Nexus-Project/Limitless-3#171]
### Describe your issue, what happened?
Ore excav no longer highlights blocks and does not provide the options gui when holding assigned keys.

### To Reproduce
1. Go to 'Use of Ore Excav'
2. Click on ' "grave" + shift and scroll '
3. Scroll down to 'ANY'

### Expected behavior
Should be able to see highlighted blocks as well as hold "grave"+Lshift and scroll in order to change shape of excavation.

### Crash Reports & Logs (Don't paste entire crash reports here.)
No crash

### Affected Version
- Pack Version:  v1.10.1
- On a server?: Singleplayer and Lan as well as local machine hosted server

**Comment by Gbergz** [comment]
You're thinking of FTB Ultimine which isn't in the pack.

**Comment by OuroborosRahu** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/82735541/115159083-09af1480-a057-11eb-9d4e-d9bf16bb3bd4.png)

This is from your own mod list

**Comment by Gbergz** [comment]
> Ore excav no longer highlights blocks and does not provide the options gui when holding assigned keys.

Ore Excavation doesn't do that. FTB Ultimine does however. You're thinking of that mod. No longer in the pack.

**Comment by OuroborosRahu** [comment]
In previous version of the pack this was a thing. It only changed with most recent update

**Comment by Gbergz** [comment]
Nothing has changed between then and now regarding ore excavation. Ore Excavation doesn't highlight blocks when you veinmine. Only if you're on 3x3, 5x5 etc. Which you need to change mode to do.

**Comment by OuroborosRahu** [comment]
I don't play FTB I played sevtech, MCeternal, D&D&SS and now TNP limitless 3. As stated in the concern there is no way to change as the GUI no longer appears. I will load previous version and record video and post.

**Comment by Gbergz** [comment]
GUI no longer appears because that's part of FTB Ultimine. Which was part of Limitless 3 until it was replaced by Ore Excavation.

FTB Ultimine: https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine

FTB Ultimine is a mod not a modpack.

**Comment by OuroborosRahu** [comment]
OOOOOOOOOOOHHHHHHHH
  My bad you said ultimine I kept reading ultimate. Okay okay on the same page now
