### ISSUE TITLE
Compacting Drawers Issue with nuggets for ingots / blocks

### ISSUE THREAD

**Issue by SyonyX-ZA** [The-Nexus-Project/Limitless-3#172]
### Describe your issue, what happened?
Issue with COMPACTING DRAWERS from mod STORAGE DRAWERS
- Certain nuggets are not available in compacting drawers if ingots / blocks are put in
   * SO FAR: Silver, Nickel, Tin, Copper, Lead (Only have encountered these 5 so far)
   * They seem to revert to THERMAL SERIES whereas all other ingots / blocks with nuggets are from various mods such as Silent's Mechanisms / Extreme Reactors and so on
   * Screenshot attached and labelled

### To Reproduce
1. Insert above mentioned items into compacting storage drawer

### Expected behavior
All nugget variants should be available in COMPACTING DRAWERS

### Screenshots
![2021-04-18_07 53 56](https://user-images.githubusercontent.com/82747040/115135901-4a3d6c80-a01c-11eb-81b8-748f02e92c31.jpg)

### Crash Reports & Logs (Don't paste entire crash reports here.)
N/A

### Affected Version
- Pack Version:  1.10.1
- On a server?: SIngle player / LAN

**Comment by Gbergz** [comment]
Still looking into this as it was not as easy to fix as I originally thought.

**Comment by Gbergz** [comment]
Think I've managed to solve this issue.
Fixed for v1.10.2 (next pack version as of now).

![image](https://user-images.githubusercontent.com/26634554/115910515-37d49000-a46d-11eb-8617-231235b7104e.png)

Thanks for the report!
**-** Gbergz

**Comment by SyonyX-ZA** [comment]
Hey,

Thank you so much for the quick response. So awesome!

**Comment by Gbergz** [comment]
fixed now, 1.10.2 out. https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3293023
