### ISSUE TITLE
DimDungeons  - can't interact with buttons or chests

### ISSUE THREAD

**Issue by Minithra** [The-Nexus-Project/Limitless-3#173]
### Describe your issue, what happened?

Cannot press buttons, open chests or other containers. Like being in a claim, but no claims in that dimension

### To Reproduce

1. Create DimDungeon Portal
2. Instert Key
3. Enter Dungeon
4. Try to open chests/push buttons

### Expected behavior

Buttons should be pressable, doors should be openable, should be able to get loot from the chests

### Affected Version
- Pack Version:  1.10.1
- On a server?: Yes, unchanged, nothing else added.

**Comment by Gbergz** [comment]
Cannot reproduce this issue.
