### ISSUE TITLE
Could galacticraft be added or a version be made with it?

### ISSUE THREAD

**Issue by Mbimajosh** [The-Nexus-Project/Limitless-3#174]
### Affected Version

- Pack Version: 
- On a server?:

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-3/issues/3

**Comment by Mbimajosh** [comment]
Ah sorry didn't notice that section or that galacticraft isn't updated but a space themed dimension mod would be nice :D
