### ISSUE TITLE
nether world kick

### ISSUE THREAD

**Issue by Awstheepic** [The-Nexus-Project/Limitless-3#177]
### Describe your issue, what happened?
for some reason, the game kicks me out randomly while in the nether, and no, didn't put anything in the files (even optifine), it says "server closed" after the loading screen.

### Expected behavior
nothing, just normal gameplay

### Affected Version
- Pack Version: 1.10.1
- On a server?: No

**Comment by Gbergz** [comment]
Do you have logs when the "kick" happens? Maybe it generated a crash report. Check for both and send them here.

**Comment by DamienTC** [comment]
im getting the same thing but its because a stadler

**Comment by Gbergz** [comment]
@DamienTC thats fixed in 1.10.2. Just released.

**Comment by Awstheepic** [comment]
Yeah sorry for being late but it's what damientrc said, sorry for not clarifying it.
