### ISSUE TITLE
Furnace "waiting for server" bug

### ISSUE THREAD

**Issue by Awstheepic** [The-Nexus-Project/Limitless-3#178]
### Describe your issue, what happened?
when I use the furnace (didn't check with other furnaces), and use coal, the game suddenly goes into "waiting for server", it never updates and when I try to quit the game (singleplayer btw) it never gets me to the main menu screen so I have to end task it, tried to see if it only occurred once for some reason but no, it happens a lot.

### Expected behavior
using the furnace normally like in vanilla mc.

### To Reproduce
1.put the items you desire to cook/smelt
2.put coal in the fuel slot
3.bowala! you get the bug

### Screenshots
![image](https://user-images.githubusercontent.com/77592110/116632343-a5962580-a95f-11eb-981c-35e202f36575.png)

### Affected Version
- Pack Version: 1.10.2
- On a server?: no

**Comment by Gbergz** [comment]
Remove FastSuite and see if it solves the problem. Known issue

**Comment by Gbergz** [comment]
Fixed in 1.10.2a
