### ISSUE TITLE
SmoothFocus breaks the FOV Effect slider

### ISSUE THREAD

**Issue by jinks** [The-Nexus-Project/Limitless-3#179]
### Describe your issue, what happened?

I'm currently using tier 4 Traveler Boots which have an insane FOV effect, so I set the slider to 10%. (The **Effect** slider in Video Settings, not the FOV slider in the main options.) After updating to 1.10.2a from 1.10.1 the slider has no effect any more. Disabling SmoothFocus makes the slider work as expected again.

### Affected Version

- Pack Version: 1.10.2 and 1.10.2a
- On a server?: Client only mod.

**Comment by Gbergz** [comment]
This is something to report on their issue tracker.
https://github.com/NotUnfound/SmoothFocus/issues

**Comment by Gbergz** [comment]
Reported it for you.
https://github.com/NotUnfound/SmoothFocus/issues/2

**Comment by Gbergz** [comment]
Fixed next pack update. Or update the mod manually on your side.

**Comment by jinks** [comment]
Thank you!

I honestly wasn't sure if the effect slider was a mod (so a pack issue) or vanilla. I didin't get to play 1.16 until a few days ago and I never even saw 1.16 vanilla. :smile:
