### ISSUE TITLE
Basic Flux Tank crashing Server

### ISSUE THREAD

**Issue by Skriton** [The-Nexus-Project/Limitless-3#18]
### Describe your issue, what happened?
Game crashed when I connecting a basic flux tank to a network. Only crashes on server, not in single player.
### To Reproduce
Place Flux controller and Flux plug into power, then place basic flux tank and connect tank to existing network.

### Expected behavior
Tank connecting to network and receiving power

### Crash Reports & Logs (Don't paste entire crash reports here.)
[crash-2020-10-25_23.03.37-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5436785/crash-2020-10-25_23.03.37-server.txt)

### Affected Version
- Pack Version:  1.6.3
- On a server?: Yes using Bisecting Host

**Comment by Skriton** [comment]
Tried just placing the Basic Flux tank and tried creating a new network with no success

**Comment by Gbergz** [comment]
https://github.com/SonarSonic/Flux-Networks/issues/399
