### ISSUE TITLE
Mana & Artifice spell interaction causing textures to break

### ISSUE THREAD

**Issue by Rhenarin** [The-Nexus-Project/Limitless-3#180]
The Mod in question is Mana & Artifice

Whilst casting a spell with M&A, textures of items as well as the character in the inventory have all changed colour to a bright green. 

### To Reproduce
Create a Self-Fling spell, tier 1 spell in M&A, in the inscription table. 
Create the spell using the wizard's chalk.
Cast spell by right-clicking with it while in hand. 
Casting it causes textures to break. 

### Expected behaviour
The spell works perfectly fine and the textures do not break. 

### Screenshots
![2021-05-04_18 20 15](https://user-images.githubusercontent.com/83637413/116977124-67a15480-ad05-11eb-938d-ff0722535291.png)
![2021-05-04_18 20 09](https://user-images.githubusercontent.com/83637413/116977139-6bcd7200-ad05-11eb-9df9-d3d9c9db269d.png)

### Affected Version
- Pack Version: 1.10.2a
- On a server?: No

### Extra notes:
Uninstalling the pack and reinstalling then proceeding to launch the same world causes the same issue. 
The first couple of seconds after loading into the world everything is working perfectly fine, the texture glitch appears after 2-3 seconds.

**Comment by Gbergz** [comment]
Turn off the Mana And Artifice Hud in the guide book to fix this problem. (Codex Arcana)

It has already been reported to the MAA author.

**Comment by jinks** [comment]
Just for completeness sake: Changing the overlay render level of Xaero's minimap (pretty far back in the settings pages) works, too.

I got it working with level 3, level 5 is supposed to work, too.
