### ISSUE TITLE
Botania Heisei Dream does not work.

### ISSUE THREAD

**Issue by danriduk** [The-Nexus-Project/Limitless-3#181]
### Describe your issue, what happened?
Placing heisei dream does not make mobs attack each other as intended

### To Reproduce
place down heisei dream supply with mana with mobs within range.
Also attempted in a creative world spawning 20+ zombies in range, a few very rarely attacked another zombie.

### Expected behavior
Mobs start attacking each other

### Screenshots
https://imgur.com/a/0eWrYak

### Affected Version
- Pack Version: 1.10.2a
- On a server?: Yes

**Comment by danriduk** [comment]
I done some digging into older mod pack versions, the heisei dream works as expected in version **1.9.7** and before from what ive test so something is breaking it from **1.9.8b** onwards

**Comment by Gbergz** [comment]
Is still happening?

**Comment by danriduk** [comment]
yup still happening in 1.10.3

**Comment by Gbergz** [comment]
Don't know what I can do to fix this. Tried to. Unable to.

**Comment by danriduk** [comment]
Looks to be working in latest release now, 1.10.4
