### ISSUE TITLE
Bountiful rewards

### ISSUE THREAD

**Issue by JoeFoxe** [The-Nexus-Project/Limitless-3#183]
I think as a main attraction to the modpack is the lootbags and I noticed that the bounty boards are pretty much useless, I collected a bunch of them at the start and never even started a quest because the rewards were never worth it. I think adding loot bags or loot bag pieces to the rewards if possible. that would really help make them useful and give players incentive to go farm out some quests for more of the lootbag addicts

**Comment by Gbergz** [comment]
Added for next update.

Example:
![image](https://user-images.githubusercontent.com/26634554/117550327-06002380-b040-11eb-8a71-23ac9442da48.png)

**Comment by Gbergz** [comment]
Thanks for the suggestion :)

**Comment by JoeFoxe** [comment]
Awesome! this will be so much fun to go farm some lootbags when all the quests are done up and make for some fun early game!

**Comment by Gbergz** [comment]
> Awesome! this will be so much fun to go farm some lootbags when all the quests are done up and make for some fun early game!

Loot bags as rewards are quite rare though, just so you know ;p

**Comment by JoeFoxe** [comment]
haha thats perfectly fine, i dont mind swinging by and looking at my bounties to see if maybe one has an extra lootbag, you could even add lootbag pieces to common/uncommon ones to give it more diversity
