### ISSUE TITLE
Getting Error On Launch With Upgrade Aquatic Installed (ver 1.10.3)

### ISSUE THREAD

**Issue by Inomz** [The-Nexus-Project/Limitless-3#184]
When I removed Upgrade Aquatic I launched with no issue. but before it gave me a forge error that said failed to enable the mod or something like that.

**Comment by Gbergz** [comment]
What Launcher?
Did you update from a previous version?
Why did you remove the issue template?
Have you tried another launcher like the GD launcher or Multimc?
Have you tried to re-install?

**Comment by Inomz** [comment]
It was a fresh install on the curseforge launcher, haven't tried any other launcher.
Not sure what you mean by the issue template?
Have not tried to reinstall but like i said just removing the Upgrade Aquatic mod made it work.

**Comment by Gbergz** [comment]
Can't reproduce this issue, but I sense its an issue with the CurseForge launcher since it always loves to have issues. Try MultiMC or GD Launcher. Works flawlessly for me and others.

**Comment by Inomz** [comment]
Ok thanks, just wanted to mention it, also about the template wasnt logged in when i hit new issue so I had to log in, then it brought me to a blank text box so thats my bad. :)

**Comment by Gbergz** [comment]
No worries. And thanks.
