### ISSUE TITLE
Server Startup

### ISSUE THREAD

**Issue by Curriem38** [The-Nexus-Project/Limitless-3#185]
On the 1.10.3 server files when I run the start.bat, everything seems to run fine. After I type true into the EULA it proceeds to do its thing, but then it hits an error. **Failure message: Mod iafgear requires iceandfire 2.0.0 or above
                Currently, iceandfire is not installed**
I believe this is the main issue that's causing the crash, even though the iceandfire version is 2.1.6 in the folder, which is above the 2.0.0 requirement.  I was wondering if there's a fix to this issue, or if there is something else wrong with the server startup as a whole or if this is only happening to me. Thanks!

https://user-images.githubusercontent.com/84214786/118345974-7baf3800-b4f5-11eb-8dc8-357e488f9e58.png

**Comment by Gbergz** [comment]
Hey! Thanks for report.
But I can't seem to reproduce this issue.
Server .bat downloads the pack and starts it up just fine. Can also join and play.

Not entirely sure what would cause you to have this particular issue..

Edit: Try to re-install the server.
