### ISSUE TITLE
Add ores to config for Mineralis ritual (astral sorcery)

### ISSUE THREAD

**Issue by ProfessorBiddle** [The-Nexus-Project/Limitless-3#187]
### Describe your issue, what happened?
Modded ores are not spawning when using the Mineralis ritual.

### To Reproduce
Use the mineralis Ritual

### Expected behavior
Modded ores should spawn

### Affected Version
- Pack Version: 1.10.3
- On a server?: yes

results of ores that are spawning, only vanilla resources created:
![heheh](https://user-images.githubusercontent.com/34872564/118413445-9cde6880-b65c-11eb-9a3f-ac1fe5980605.PNG)

this should be fairly simple to fix, ores and spawn weights can be added to the server config for astral.

thanks for everything, loving the pack!

**Comment by Gbergz** [comment]
I might do this, not a promise though. Thanks for the suggestion!
