### ISSUE TITLE
SGEAR: Suggestion for pack config Compatibility.

### ISSUE THREAD

**Issue by OracleHisty** [The-Nexus-Project/Limitless-3#188]
With Silent Gear, there are quite a few materials in the SGEAR tag that have no catagories. Dragonsteel is an example. It should be considered a metal, but is not. 
![image](https://user-images.githubusercontent.com/59514248/118544064-bba33480-b71a-11eb-95e0-9f9c788d5dcf.png)

There are quite a few ingots in the SGEAR tag that should have catagories, which make the material slightly more useful.
![image](https://user-images.githubusercontent.com/59514248/118543893-85fe4b80-b71a-11eb-87c6-764d4375fcf1.png)

It is probably in the SGEAR config for it, so its a fairly easy fix for the most part. Its just a little tedious.

**Comment by Gbergz** [comment]
Dragon Steel as a material is an addon so it's probably because of that.
https://www.curseforge.com/minecraft/mc-mods/dragon-gear

Don't think there's much I can do.

**Comment by OracleHisty** [comment]
> Dragon Steel as a material is an addon so it's probably because of that.
> https://www.curseforge.com/minecraft/mc-mods/dragon-gear
> 
> Don't think there's much I can do.

If I can figure out how from the wiki, would it be okay if I compile a datapack for numerous resources to be fixed and if I succeed, can you make it in the pack. Silent's Gear items and materials _can_ be manipulated in datapacks.

Edit: 2 seconds in, I forgot to say the screenshots are on the Official EU server for the pack
