### ISSUE TITLE
Charged Certus Quartz Dup Bug

### ISSUE THREAD

**Issue by rgdelta1973** [The-Nexus-Project/Limitless-3#189]
I am reporting this first as I am not sure if or which mod if any causing this

### Describe your issue, what happened?
You can dupe Charged Certus Quartz with Iron Barrel and Cardboard Box

### To Reproduce
1. Put down Iron Barrel
2. Put Charged Certus Quartz inside Iron Barrel
3. Place Cardboard Box on Iron Barrel
4. Collect Certus Quartz that Pops out
5. Remove Cardboard Box
6. Collect Certus Quartz inside Barrel
7. Rinse and Repeat

### Expected behavior
Should not be duping the Charged Certus quartz

### Affected Version
- Pack Version: 1.10.3
- On a server?: No Single Player

**Comment by Gbergz** [comment]
Thanks for the report, but not sure if I can fix this on my end. Would probably need to be reported to one of the mods used. Not sure which one though.
