### ISSUE TITLE
Server Crashes in the nether

### ISSUE THREAD

**Issue by critch646** [The-Nexus-Project/Limitless-3#19]
### Describe your issue, what happened?
After wandering in the nether for several minutes, the server lags and crashes, sending players to the main screen.

### Crash Reports & Logs
https://pastebin.com/m8AihSvG
https://pastebin.com/PrwVbqDj
https://pastebin.com/5YLHJC5i

### Affected Version

- Pack Version:  1.6.2

**Comment by Gbergz** [comment]
Hey,
Try changing ``max-tick-time=60000``in overrides.properties & server.properties to ``max-tick-time=180000``

**Comment by MokahTGS** [comment]
we change our max tick time to -1 to turn watchdog off completely.
