### ISSUE TITLE
Anvil Enchanting needs that one rebalance mod back.

### ISSUE THREAD

**Issue by OracleHisty** [The-Nexus-Project/Limitless-3#190]
I am sitting here, re-enchanting my armor on the Official EU, and ALL my enchants are costing 250+ levels. In previous versions it would be around 10 or 20 per enchant, but this is atrocious.

![image](https://user-images.githubusercontent.com/59514248/118925253-059b3e80-b904-11eb-8120-455b061d1227.png)
THIS IS ONLY ENCHANT NUMBER 2

**Comment by HistoireTheOracle** [comment]
crud, the screenshot didnt clip right
here is the right one:

**Comment by OracleHisty** [comment]
I found a way around it. I needed to replace all the parts of my gear, then re-create them from the parts. It reduced it down to safe levels. _Literally..._
