### ISSUE TITLE
Changing some stuff/pack version breaks the option to play via LAN/Multiplayer

### ISSUE THREAD

**Issue by TheMasterTM69** [The-Nexus-Project/Limitless-3#191]
So, one time i updated the pack with my friend and the old world we were playing on was unplayable for us both (i could still easily load in) because when he tried to join it would say that Data does not match or something (we were on the same version and even re-installed the pack)

I have no idea what is causing this issue as probably doing any change to the pack/mod could cause this.

And im not even sure how to fix it beside just making a new world and losing all the progress.

**Comment by Gbergz** [comment]
Can you send the logs when that message appears? From the user that gets the message.

**Comment by TheMasterTM69** [comment]
uh this message appears on my friends screen when he tries to join the server.
but this is the latest log which generates in my folder (since this isnt running on a dedicated machine but just via lan)
https://www.dropbox.com/s/dzu0upfwlg8guk7/latest.log?dl=0
maybe this will help in some way.
I'll try to get the message that appears on screen from him in a bit

**Comment by TheMasterTM69** [comment]
And this is his log.
I noticed that at the end it shows up with Tetra stuff that got deleted in the last version, but this new world was made on the newer version which didnt include tetra which is really weird.
https://www.dropbox.com/s/dzu0upfwlg8guk7/latest.log?dl=0

**Comment by KHowl** [comment]
I have the Same issue, complaining about Tetra stuff. Ive attached the log from my friends attempt at joining via Lan as well we both downloaded the same update and I made sure we had the same mods.
[latest.log](https://github.com/The-Nexus-Project/Limitless-3/files/6549289/latest.log)

**Comment by Gbergz** [comment]
Looks like the client that are trying to join has Tetra installed. That mod was removed in the latest update. Try doing a re-install on the client then try again.

**Comment by KHowl** [comment]
They have the Latest version 1.10.3 and no Tetra installed. I dont have it either. Its to do with bringing a world from 1.10.2a over to 1.10.3 as I created a new world and they can join fine but we cant play on our old world.

**Comment by SquTM** [comment]
Did you only just update the pack and this happened or have you been playing on the new update for a while now?

**Comment by KHowl** [comment]
I only just updated

**Comment by TheMasterTM69** [comment]
Aaaand after updating from 1.10.3 > 1.10.4 the world basically breaks the ability to connect again.
The latest.log mentions few blocks from twilight and *cfm* whatever that is. every time there is an update which removes some blocks from the world basically prevents everyone beside the world owner from connecting even tho the blocks themselves no longer exist in the world. this is what shows up on the client screen when they try to connect. there is no fix for this other than creating new world and losing progres.. it's just frustrating.
![image](https://user-images.githubusercontent.com/75620187/120101895-c2816c80-c148-11eb-8d21-dfbd1f7f39f2.png)

Edit: Pack wasn't directly updated, i specifically checked "Update to new profile" on forge to prevent the complete loss of this world and also to make sure some mods were not messed up with version or whatever.
Edit 2: I think i came to the conclusion that the level.dat (player inventories/world gen) are the issue? since i made a new world to test it with my friend and it worked fine, i moved the level.dat to the new world and after that he couldn't join. A rather interesting issue...

**Comment by KHowl** [comment]
Same issue and i Updated on the same profile, not a new one...

**Comment by Gbergz** [comment]
re-add tetra, since it looks like its that breaking.

**Comment by KHowl** [comment]
Its not tetra that is the issue any more. We are now on a new world and tried updating to 1.10.4 but its done the same thing on the new world, Complaining about the Woodcutter, crm trampolines and a twilight boss spawner. Its the worlds when the versions update.  
![image](https://user-images.githubusercontent.com/68691432/120228884-eecde380-c243-11eb-989d-159e5a71e298.png)

**Comment by KHowl** [comment]
Creating a new world causes no issues and we can play fine, but bringing a world over from a previous version causes issues

**Comment by Gbergz** [comment]
Yep those blocks were removed in the update. Which is not an issue. Should work.

**Comment by Gbergz** [comment]
Should try another launcher if you're using CurseForge. Like MultiMC or GD Launcher. Then also a fresh server installation. Transfer over world and the maessentials folder.  And any other things you need carried over.

**Comment by TheMasterTM69** [comment]
It's not a launcher issue. 
The issue is, that every time the world generation is updated you (as a client) cannot join the host for some reason. if a mod is removed (and blocks with it) they just turn into air blocks in the game so it's not an issue because a mod was removed or something.
If you plan on updating the pack in the future please and don't do anything with world generation again(at least for one update) so we can see if that's the actual issue because from my testing it actually is the world generation that's causing this issue. There is a not so simple fix at the moment for this to keep playing on the old world however. All you need to do is transfer your inventory to a chest (so you dont lose your items), create a new world and move the level.dat from the new world over to the old world folder. (There is only a few issues with this. (1. you lose extra hearts 2. Since there is new world gen you will encounter glitches related to that)

**Comment by Gbergz** [comment]
Welp, wish I could help. But since I don't know what the heck it could be. It's harder. Also never encountered the issue before. I've updated the official server countless times. Never had an issue like this before. It just looks like from the stuff you've sent that the client is missing mods, or server is. Because the "missing registry" is just mods that have removed parts of their mod, which isn't the issue here apparently. It's something else. 

Sorry you're having issues.

**Comment by TheMasterTM69** [comment]
I also have never encountered this issue before on any modpacks, i looked for a bit on the internet regarding the same issue but they were all dead-ends basically as most of the people suggested that {its a wrong mod version} or {something doesn't match or whatever.}
The fix i suggested is probably(?) the only way to play on the old worlds. (i tried moving different stuff around with no luck)
So if anyone is looking to continue their adventure on an old world (multiplayer cuz single works fine after updating) just try my fix and you should be about fine for now.

**Comment by KHowl** [comment]
Ive went through the trouble of creating a new world and tranfering everything over through a NBT editor for the 10.2 -> 10.3 update, but now im thinking i might just need to copy the registry from a fresh world on a 10.4 world to the old world and see what that does. We have gone back to 10.3 until i can transfer to the latest update without issues.

**Comment by KHowl** [comment]
@TheMasterTM69 I have found a simplier fix to yours if you want it and want to keep your hearts. If you have the NBT editor, load a new world and copy the fml folder from the new worlds level.dat over to your old worlds level.dat. This will fix the registry problem and allow you to keep your (the hosts) progress :D Still dont know why the world generation is causing this on each update but thought i would share a simplier fix to save on losing progress
