### ISSUE TITLE
Iron Jetpacks Quest Progression

### ISSUE THREAD

**Issue by Jwilson106** [The-Nexus-Project/Limitless-3#193]
So it's not really broken but the progression to go from a stone or copper jetpack requires advanced coils to make the next tier (Iron, Bronze, Silver) but the quest for the coils is gated by making the third tier jetpacks.

![2021-06-11_10 18 36](https://user-images.githubusercontent.com/63497105/121726330-40296e80-ca9f-11eb-9bca-0fd39ec191bc.png)
![2021-06-11_10 18 41](https://user-images.githubusercontent.com/63497105/121726335-415a9b80-ca9f-11eb-86f9-734aecd6de6a.png)
![2021-06-11_10 20 05](https://user-images.githubusercontent.com/63497105/121726337-41f33200-ca9f-11eb-85a4-da93e9f3632a.png)

Hopefully the pictures make sense.

**Comment by Gbergz** [comment]
That chapter is really a mess and I will remake it in the future.
And that recipe must've changed since it wasn't like that when I originally created the chapter. 🤔

**Comment by Gbergz** [comment]
That being said, I will look into this in the future. But thanks for reporting! 👍
