### ISSUE TITLE
[Suggestion] Ability to make marble using Pedestal's cobble gen

### ISSUE THREAD

**Issue by Shindur** [The-Nexus-Project/Limitless-3#194]
So I noticed that in the configs Astral Sorcery marble isn't generating in the world, I assume this is for compatibility reasons. Thus the only way to get marble is by destroying the various structures from Astral. While this may work for getting by using the mod, what if we wanted to build with it? We'd have to scour the landscape in hopes more structures generate. 

Is there a way we could use the cobble gen from Pedestals, whether normally or with a silk touch enchant, to make more marble?

**Comment by Gbergz** [comment]
You can convert Quark marble to Astral marble just by placing quark marble in a crafting grid. And vice versa.

**Comment by Shindur** [comment]
I saw that, but how rare is quark marble? Or rather does it only spawn in specific biomes?

**Comment by Gbergz** [comment]
Quark Marble is found in Plains biomes.

**Comment by Shindur** [comment]
Got it, thank you!
