### ISSUE TITLE
I cant kill my goddamn dogs for morgan

### ISSUE THREAD

**Issue by kookoe** [The-Nexus-Project/Limitless-3#195]
### Describe your issue, what happened?
 I was playing on a server before it updated to the recent version of tnp 3 which is 1.10.4. For some reason after updating to this version, I can't hurt any of my dogs on the server. I also tried to get a morgan but like the same issue prevents me from getting one. So I cant make a dog torture chamber and I cant get my morgan. I don't know why its like this but I used to kill a bunch of my dogs all the time before the update to 1.10.4 on the server? Is this bugged or something was changed that prevented dogs from dying? 

### To Reproduce

update to 1.10.4
tame a dog in survival mode on the server
try punching the dog

### Expected behavior
i can kill the damn thing and get a very nice morgan

### Affected Version
- Pack Version: 1.10.4
- On a server?: 1.10.4

**Comment by Gbergz** [comment]
Fixed next update. Stay tuned.
