### ISSUE TITLE
1.10.5 Ice and Fire continually crashing server

### ISSUE THREAD

**Issue by Shindur** [The-Nexus-Project/Limitless-3#197]
### Describe your issue, what happened?
After updating my server to 1.10.5 Ice and Fire seems to be continually pathfinding entities. This is causing a crash due to the server running out of memory and heap space. It's a 6GB RAM server.

### To Reproduce
1. Update from 1.10.4
2. Server continually has logs of ice and fire mobs pathfinding
3. Ser hangs up continually
4. Crashes

### Expected behavior
For the server to not hang and crash like this.

### Screenshots
None

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/RijiGEd1

### Affected Version
- Pack Version: 1.10.5
- On a server?: Yes

**Comment by Shindur** [comment]
Seems like this was caused by some Myrmex's that were chunkloaded at spawn. I went to the area and just used /kill to kill all of em off, hasn't crashed yet but will update if it does.

**Comment by Gbergz** [comment]
Looks like you've ran out of memory, I would allocate more than 6gb, 8-10.

**Comment by Shindur** [comment]
Just for reference.. typically a server doesn't need as much RAM as the pack takes to run on a client.. The issue was solved after killing those entities at spawn, but the Ice and Fire pathing was what was taking up all the RAM for some reason or another.
