### ISSUE TITLE
Dupe Bug (affects blocks and technically items)

### ISSUE THREAD

**Issue by AxolotlKing** [The-Nexus-Project/Limitless-3#198]
### Describe your issue, what happened?
By using the corrupterite pickaxe with fortune VIII, Luck II, and Serendipty III (Serendipity is just another form of luck) I am able to dupe any block I mine that is able to be siphon into my inventory (siphon is a enchant that teleports mined blocks into your inventory).

### To Reproduce
1. Combine Fortune VIII, Luck II, Serendipity III and, Siphon onto a corrupterite pickaxe
2. Mine any block that can be siphoned into your inventory
3. The block you mined gets duped

### Expected behavior
You only get 1 block instead of 2

### Screenshots
Here's a video of the dupe.
https://www.youtube.com/watch?v=ImPusyC-Qo4

### Affected Version
- Pack Version:  1.10.5
- On a server?: yes (the official NA server)

**Comment by Gbergz** [comment]
Dupes are always fun, would say not to use it but thats up to you ofcourse. Not sure how I would fix this. Might be something the mod author of those enchantments need to fix since it seems to be a cross enchant interaction?

**Comment by Gbergz** [comment]
This has been reproduced with only upgraded netherite + vanillatweaks siphon enchantment. I've reported it to the mod author, we'll see if it can be fixed.
