### ISSUE TITLE
Update to 1.10.5 - game crash when atacking mobs with SilentGear sword

### ISSUE THREAD

**Issue by x0tempus0x** [The-Nexus-Project/Limitless-3#199]
Hi,

first of all, fine modpack, i enjoy it very much.

As written in the header, i updated to the newest version and constantly my games crashes, as soon as i try to hit a mob with a silentgear sword, made of dragoningots. It has some enchantments on it, but this was no problem in 1.10.4 (and i downgraded back to 1.10.4 because of the crashs).

Crashlog is attached.   
[crash-2021-06-13_08.06.02-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/6643461/crash-2021-06-13_08.06.02-server.txt)

Gz. Temp

**Comment by Gbergz** [comment]
Report to the mod author.
https://www.curseforge.com/minecraft/mc-mods/dragon-gear

**Comment by Gbergz** [comment]
Will probably get it fixed faster, thanks for report.

**Comment by Partonetrain** [comment]
Fixed, sorry for the wait.

**Comment by x0tempus0x** [comment]
Works like a charm again. Many THX.
