### ISSUE TITLE
Woot mob farm loot table UI congestion

### ISSUE THREAD

**Issue by Skriton** [The-Nexus-Project/Limitless-3#20]
### Describe your issue, what happened?
Woot factory heart has icons and tooltips overlapping with multiple mob controllers installed.

### To Reproduce
add enough mob controllers so that the possible loot options exceed the number of slots available.

### Expected behavior
Possibly extend the loot window or add pages or scrolling option.

### Screenshots
![2020-10-26_02 04 30](https://user-images.githubusercontent.com/36782597/97139145-9a580800-1738-11eb-93d5-32e431d720a9.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
No Crash

### Affected Version
- Pack Version: 1.6.3
- On a server?: Yes

**Comment by Gbergz** [comment]
Hey, thanks for report but this is something you should report on Woot’s issue tracker.

**Comment by Skriton** [comment]
I will forward it in that direction
