### ISSUE TITLE
1.10.5 Generating new Chunks Crashes Server

### ISSUE THREAD

**Issue by ghost** [The-Nexus-Project/Limitless-3#200]
### Describe your issue, what happened?
Generating new Chunks Crashes Server
Server Got Updated from 1.10.4
Only applies to Overworld

### To Reproduce
On a already existing map from 1.10.4 updated..just fly into a new chunk and the server crashes

### Expected behavior
chunks generating normally

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/zXSZjxQh

### Affected Version
- Pack Version: 1.10.5
- On a server?: Yes

**Comment by ghost** [comment]
After Some testing around i was able to fix the issue and stop it from crashing

I found 2 fixes so far:

1.
To fix the issue i removed the mod Better Caves that was added in 1.10.5

After deleting the mod all chunks that were tried to generade are corrupted and need to be deleted manually...with a tool like MCA selector

2.
Editing the nbt data of the server and change the world generation type from quark:realistic to minecraft:noise
removing the mod bettercaves doesnt need to be removed in this one

**Comment by Gbergz** [comment]
So the solution to this right now is to use an NBT Editor and change the level-type in level.dat & level.dat(old) from `quark:realistic` to `minecraft:noise`. Like explained above in 2nd option.

**Edit:**
Drag level.dat into the NBTExplorer window. Go into `+Data` **->** `+WorldGenSettings`, **->** `+dimensions`, **->** `+minecraft:overworld`, **->** `+generator`, **->** look for `quark:realistic`. Change that to: `minecraft:noise`. 
Hit `save`. **(Do this for both level.dat & level.dat(old).**

> Doing this will get you a small or big worldgen border depending on the biome, but the world will work fine.
