### ISSUE TITLE
1.10.4 -> 1.10.5b Can't load into old world after update (SP)

### ISSUE THREAD

**Issue by TheMasterTM69** [The-Nexus-Project/Limitless-3#201]
After updating to the new version i wanted to play on my old world but the loading keeps getting stuck on 97% and won't move further.
![image](https://user-images.githubusercontent.com/75620187/121812460-1ec7ae80-cc68-11eb-80b8-6c329c923a3c.png)
The game isn't frozen since i can see the tips switching.
I waited about 20-30 minutes and nothing changed so i don't think its possible to load in.

No idea how to fix this currently.

**Comment by Gbergz** [comment]
Have you tried restarting?

**Comment by TheMasterTM69** [comment]
The game or my PC? since i restarted my game a few time already

**Comment by Gbergz** [comment]
Well, the game. But try restarting PC aswell wouldn't hurt. 
Also what launcher are you using? If you're using CurseForge try using MultiMC or GD Launcher, transfer world to it.

**Comment by TheMasterTM69** [comment]
I'm using curse, but right now i'll try updating it to a new profile and porting the world there to see if it does anything

**Comment by Gbergz** [comment]
Oh and also, updating existing profiles are generally a bad idea, things can fail to download or files fails to get replaced. I always recommend creating a new profile every update then just transferring important stuff like the world, settings etc to the new profile.

**Comment by TheMasterTM69** [comment]
aand nope, didn't help, still gets stuck at 97% ;-;

**Comment by Gbergz** [comment]
How much ram allocated?

**Comment by TheMasterTM69** [comment]
max curse can so 12GB since i dont want to manually change every time i play

**Comment by Gbergz** [comment]
mind sending the logs when its stuck at 97?

**Comment by TheMasterTM69** [comment]
It's world gen again according to logs

**Comment by TheMasterTM69** [comment]
Making a new world works fine as it should, no problems there beside the fact that i want to play on my old world ;-;

**Comment by Gbergz** [comment]
> mind sending the logs when its stuck at 97?

can I have them?

**Comment by TheMasterTM69** [comment]
[latest.log](https://github.com/The-Nexus-Project/Limitless-3/files/6644226/latest.log)

**Comment by Gbergz** [comment]
follow this small tutorial
should fix it!

https://github.com/The-Nexus-Project/Limitless-3/issues/200#issuecomment-860216359

**Comment by TheMasterTM69** [comment]
oh yeah, that doesnt fix it, i tried it already

**Comment by Gbergz** [comment]
It will definitely fix it, the guy in that issue has the same crash. Fixes it.

**Comment by TheMasterTM69** [comment]
instead of a quark generation error it gives a minecraft;noise error

**Comment by TheMasterTM69** [comment]
the thing is that the guy in that thread can actually load into the world, i cant even to that

**Comment by Gbergz** [comment]
Your crash is the exact same, just checked. Doing that thing will most likely fix it. Try agian.

**Comment by TheMasterTM69** [comment]
![image](https://user-images.githubusercontent.com/75620187/121814646-72d79080-cc72-11eb-8c18-b3a6ad6b0503.png)
Yeah, it works
![image](https://user-images.githubusercontent.com/75620187/121814751-fdb88b00-cc72-11eb-8a19-dbd522b0c019.png)
It would probably work if i could load into the world in the first place. but i cant

**Comment by TheMasterTM69** [comment]
what i can try though, is:
1. load the world on .4
2. change the gen type in .4
3. load again on .4
4. port over to .5 (if the world loads after step 3.)
5.??
6. Profit?

**Comment by TheMasterTM69** [comment]
POV: It didnt work
![image](https://user-images.githubusercontent.com/75620187/121815900-eda3aa00-cc78-11eb-8891-ac85d881ce58.png)

**Comment by TheMasterTM69** [comment]
When i doubt just replace the level.dat from a new world.
![2021-06-13_19 19 30](https://user-images.githubusercontent.com/75620187/121816499-52143880-cc7c-11eb-985a-db9e8d9c140a.png)
*It just works*
but yeah, it shouldn't be like this.
please man, i beg you, don't change anything with world gen for one update. just for testing purposes.

**Comment by Gbergz** [comment]
So, did you get this solved or not? Fixed by replacing the level.dat?

**Comment by TheMasterTM69** [comment]
Yeah, but that was the only way to fix it im pretty sure. changing anything else didnt work, had to make a new world on .5 and replace the level.dat from the new world to my old world to make it work.
