### ISSUE TITLE
Crash the server by eating an apple

### ISSUE THREAD

**Issue by AxolotlKing** [The-Nexus-Project/Limitless-3#202]
### Describe your issue, what happened?
Eating an ender apple crashes the server
### To Reproduce
1. Eat Ender apple
2.  crash
4. Internal Exception: java.io.IOExeption: An existing connection was forcibly closed by the remote host

### Expected behavior
you gain saturation, hunger and it leads you to a stronghold

### Screenshots
![2021-06-13_18 11 12](https://user-images.githubusercontent.com/85012822/121828504-9ef41100-cc74-11eb-8dc0-7ae2cbf66512.png)

### Affected Version
- Pack Version: 1.10.5c
- On a server?: Offical NA server

**Comment by Gbergz** [comment]
Reported this issue to the mod author.
