### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by Yeeacub** [The-Nexus-Project/Limitless-3#206]
### Describe your issue, what happened?
I'm just inside my base crafting things for my powah reactor and it brings me to a server menu. Middle server says cant resolve hostname. This has happened twice within 20 minutes. The first time it happened I was confused as I was holding a furnace from fast furnace and went to go look at the block I wanted to place on but couldn't because it brought me to the server menu after me waiting staring at the backdrop of the loading screen with no text. I then went to my worlds to get back on but it asked me to make a new world as if I didn't have any worlds in the first place. Also I'm playing SINGLEPLAYER. Before the second launch it was giving me errors when I clicked on the modpack and wouldn't let me load it. It was saying something about "javaruntimeerror" cant quite remember. After testing a couple other modpacks I realized it wasn't an issue on my part. I then went to go launch TNP limitless again and it loaded just fine. Note: when I went to go launch it, it crashed immediately. Before that moment I had my RAM set to 12G (I set it to 12G in the past). I then set it to 10G and it launched. Played for awhile running around my base crafting things and it crashed again. **Seems to be hyppogryph from ice and fire. I will be contacting them as well. Hope this gets fixed soon i love this modpack!**

### To Reproduce
1. Go to 'N/A'
2. Click on 'N/A'
3. Scroll down to 'N/A'

### Expected behavior
Not to crash when im randomly crafting random things.

### Crash Reports & Logs (Don't paste entire crash reports here.)

First crash:
https://paste.ee/p/ErL7t

Second crash
https://paste.ee/p/m1HkZ

### Affected Version

- Pack Version: 1.10.5c
- On a server?: No

**Comment by Gbergz** [comment]
This is a Ice and Fire crash tied to the Hippogryph mob.
Report it on their issue tracker and it might get fixed eventually.
Or if you're on singleplayer. Try updating the mod as an update was recently released.

And the server in the middle is supposed to have no server. It's like a line break.

**Comment by Yeeacub** [comment]
I
