### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Watermelooohn** [The-Nexus-Project/Limitless-3#208]
Randomly every 5-60 or so minutes my game will freeze and then crash. It used to just freeze for 10 seconds which I didn't mind but now it crashes

**Comment by Gbergz** [comment]
Yeah, these kind of reports I really can't do anything about. You removed the issue template + the info you've given me doesn't really help at all.

Open a new issue and try to investigate more, and dont remove the bug report template.
