### ISSUE TITLE
pack version 1.10.6 doesn't download/install vanilla 1.16.5 resulting in crashes on fresh install. 

### ISSUE THREAD

**Issue by BrettMoan** [The-Nexus-Project/Limitless-3#210]
Not sure what about the pack is causing this, but i wasn't able to get the latest version to load, until I **manually ran a vanilla 1.16.5 instance** 

until i ran a **a vanilla 1.16.5 instance** i couldn't even get past the "deep scan" and get the normal crash log. the **only** log i can get is the `C:\Users\%user%\curseforge\minecraft\Instances\TNP Limitless 3 - 1.16.5\logs\latest.log`

I'm not using optifine.

### Describe your issue, what happened?
Pack fails to load on a brand new fresh install of minecraft

### To Reproduce
1. On fresh install (delete pack, uninstalled Curseforge, uninstalled system minecraft, uninstalled java, then reinstalled latest oracle 1.8 java, then Minecraft, then curseforge, then TNP) 
2. set GB settings to recommended 7-9 GBs
2. Attempt load of TNP
3. Game crashes at pre-load during Deep scans. Around the "Deep scan of pachouli". 

(Other mod packs load just fine. will attempt to reinstall previous version of TNP and other 1.16.5 packs to help isolate the issue as something relating to the current pack/mods.)

### Expected behavior
No crashing.

### Screenshots
Video of crash:

#### Static image shortly before crash
https://i.imgur.com/kAgoVkL.png

#### 40 sec click of full attempt with crash
https://live.staticflickr.com/65535/51290423593_25b12cebde_o.gif

### Crash Reports & Logs (Don't paste entire crash reports here.)
full : https://pastebin.com/5GHGrCcX
potential culptrit:
```
[16:25:52] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: net/minecraft/util/math/ChunkPos
```

### Affected Version
- Pack Version:  1.10.6
- On a server?: No

**Comment by Gbergz** [comment]
CurseForge tends to have issues sometimes. Try MultiMC or GD Launcher.
