### ISSUE TITLE
Sink from Cooking for Blockhead didnt work

### ISSUE THREAD

**Issue by Sergent78** [The-Nexus-Project/Limitless-3#211]
### Issue

The sink from Cooking for Blockhead didnt work. It don't provide any water.

### To Reproduce
- Craft and place a Sink
- use a Mechanical Pipe or anything else to extract some water. 
- Result into an 0 mmb/t extracted. And 0 mmb/t produced.

### Screenshots
![image](https://user-images.githubusercontent.com/39702822/124607561-4298a180-de6e-11eb-8ab6-c723044d748d.png)

### Affected Version
- Pack Version: 1.10.6
- On a server?: Yes

**Comment by Gbergz** [comment]
It isn't supposed to give unlimited water.

Use the infinite water source instead, place a tank beside it.

**Comment by Sergent78** [comment]
In the past it always gave unlimited water. Its the first Modpack it didn't

**Comment by Gbergz** [comment]
Yes, that is true. In this pack it's turned off.
