### ISSUE TITLE
Firecharge Rod crashes server

### ISSUE THREAD

**Issue by llama-ninja** [The-Nexus-Project/Limitless-3#214]
**Describe your issue, what happened?**
Went to use Firecharge Rod from Craft and Hunt, which crashed the server

**To Reproduce**
Place firecharge rod in offhand and right click

**Expected behavior**
No crashing.

**Crash Reports & Logs (Don't paste entire crash reports here.)**
https://pastebin.com/MCp31nH5

**Affected Version**
Pack Version: 1.10.6
On a server?: Yes

**Comment by Gbergz** [comment]
Fixed next update.
