### ISSUE TITLE
soft fall enchant takes my full hunger bar when i fall.

### ISSUE THREAD

**Issue by MasterPrzecin** [The-Nexus-Project/Limitless-3#216]
When i fall from random hight without jumping my character is making tons of particles under me like i was falling all the time 1000 times per sec and it takes my whole hunger bar in 2-3 seconds. It stops when i jump. i have shoes with soft fall enchant only and it shows up only when i have this shoes on.

**Comment by Gbergz** [comment]
`Soft Fall | Eliminates falling damage, downside is that it gives exhaustion. (Saturation Drain.)`

Working as intended though it might be a bug in the mod that it drains so much.

Report it on their issue tracker: https://github.com/Maciej916/Ma-Enchants/issues
