### ISSUE TITLE
aquaculture ticking entity error

### ISSUE THREAD

**Issue by DemgelZalvine** [The-Nexus-Project/Limitless-3#22]
### Describe your issue, what happened?
This one was just a random pop, and to be honest likely not very repeatable. Adding it since I already raised the molten glass issue, and may as well add in this one.

### To Reproduce
Unfortunately this hasn't happened again. Adding the crash log just as it exists.
Seems to have occurred at random, not sure if faulty AI behavior or..?

### Expected behavior
Fish being fish

### Crash Reports & Logs (Don't paste entire crash reports here.)
[crash-2020-10-27_23.01.09-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5450412/crash-2020-10-27_23.01.09-server.txt)

### Affected Version
- Pack Version: 1.6.4
- On a server?: Yes.

**Comment by Gbergz** [comment]
Mind reporting it here? https://github.com/TeamMetallurgy/Aquaculture/issues

**Comment by DemgelZalvine** [comment]
> 
> 
> Mind reporting it here? https://github.com/TeamMetallurgy/Aquaculture/issues

No problem. Done!
