### ISSUE TITLE
ores disappearing when I collect them

### ISSUE THREAD

**Issue by kauepsoares** [The-Nexus-Project/Limitless-3#221]
some ores like diamond, lapis lazuli, quartz and some others disappear when I collect them, they drop normally but don't show up in my inventory

**Comment by Gbergz** [comment]
That's weird for sure, but don't remove the issue template. It's made for a reason.

Couldn't tell you why that would happen, maybe you're wearing some kind of item. It's not really reproducable.

**Comment by kauepsoares** [comment]
I created a new world and it worked normally. I tested unequipping all the items and the problem continued, I have no idea why this happened

**Comment by Gbergz** [comment]
Hm. Weird. Well it's something since it's working in your new world.
