### ISSUE TITLE
Opening the AE2 pattern freezes/crashes the game.

### ISSUE THREAD

**Issue by TheMasterTM69** [The-Nexus-Project/Limitless-3#223]
I recently set up my AE2 but when i tried to open my pattern terminal to start setting up some autocrafting my game just froze.
Im on 1.10.7 and never had any issues with AE before so i have no idea whats going on.

I could suspect refined storage but that would be weird right? (i used RS before setting up AE)
i tried updating the mods or something but that basically breaks half the mods so i reverted it back.

Is there a way to see what causes this or to fix this?
Can't even get a log going since the game freezes and doesnt crash so i have to kill it with a task manager.

**Comment by Gbergz** [comment]
Try removing the mod Performant

**Comment by TheMasterTM69** [comment]
Will do, but to test if it works after removing a need a solid 15-20 minutes because loading times..

**Comment by TheMasterTM69** [comment]
Hmm.. i was able to open the terminal now a few times without the game freezing on me, but every time i do try to open it i get a massive lag spike
