### ISSUE TITLE
Single player freezes when trying to hatch an Ice and fire dragon

### ISSUE THREAD

**Issue by alejandro-esquivel** [The-Nexus-Project/Limitless-3#224]
### Describe your issue, what happened?
I've obtained an Ice and Fire Dragon Egg, I have put it in the ground with the required conditions for it to hatch and after a while the game's server stops responding(I can move but can't use stuff), I've seen another issue related to the single player server freezing because someone had a bow with the true enchantment(I have a dragon bone bow with the true-shot enchantment and think that might be related to the freeze).

### To Reproduce

1. Deploy an ice and fire electric dragon egg on the ground with the requiring criteria for it to hatch.
2. Wait a minute or two
3. The game's server stops responding

### Expected behavior
I expected the dragon egg to hatch, but it didn't.

### Screenshots
No.

### Crash Reports & Logs (Don't paste entire crash reports here.)
[latest.log gist](https://gist.github.com/aleaallee/c0f46e9304ca8c0263194323e45ff0d9)

### Affected Version

- Pack Version: 1.10.7
- On a server?: No

**Comment by Gbergz** [comment]
Try downgrading Citadel to version `1.7.1`

**Comment by alejandro-esquivel** [comment]
> Try downgrading Citadel to version `1.7.1`

It worked, thanks!!

**Comment by Gbergz** [comment]
Awesome, closing then. :)
