### ISSUE TITLE
Singleplayer game disconnected from itself (?)

### ISSUE THREAD

**Issue by Slotherak** [The-Nexus-Project/Limitless-3#225]
### Describe your issue, what happened?
Singleplayer game frequently “disconnects from server”, or incorrectly states that the server was closed (it most certainly was not, or else I would be blue-screening right now). 

Most recent attempt, I was trying to slay an Ice dragon from Ice and Fire, with a weapon from Silent Gear, wearing armor from vanilla, TiC, and Blue Skies, and with several rings from Rings of Ascension equipped. Also was equipping a spellstone from Enigmatic Legacy, the one that reflects 50% of projectiles, and the magnet ring from the same mod. And as I am slashing at the beast behind my half-witted barricade of cobblestone and frozen stone, I am kicked out of the game and staring at the loading screen tips (sans background). Almost immediately after that, the game force quits on its own and announces that the game has crashed with exit code 0. (Real helpful, I’m sure they thought. Exit code zero means there was no explicable error on the code’s side, but then why did it crash? Slashing a dragon’s hit box with a silent gear Diamond sword is that destructive to the game’s code? Or was I wearing the wrong ring combos? Will update this bug report if I can nail down exactly what issue is causing the crash)

### To Reproduce
Unknown steps to reproduce. Prior instances involved using JEI to look up Manaweaving Altar recipes, which I assumed was a Mana and Artifice-JEI incompatibility, but this makes me wonder if something modpack-breaking happened. Had to update to this version in the hopes of restoring a corrupted save of the previous version, which would crash upon entering the Outer End. No, this is a fresh(ish) file. Same seed, new attempt. About a week old, 79 Minecraft days old. 

Also only have 12 gigs of Ram total so all I can spare is 8-10 gigs of Ram for allocating. Is that where the problem lies?

### Expected behavior
I don’t know how much clearer it can be than saying not getting disconnected from a game that is hosted on my own computer, but that’s what I was expecting. Never seen this before. How did the server close on my own laptop computer? I am not using any kind of vpn, or cloud computing service, just regular singleplayer usage. Did the connection to CurseForge fail, and if so, why would that halt a game on my device that already has all the requisite data loaded locally? 

### Crash Reports & Logs (Don't paste entire crash reports here.)
 No linkable crash report.

### Affected Version
- Pack Version: 1.16.5
- On a server?: No

**Comment by Gbergz** [comment]
The dragon kill might be solved by downgrading Citadel to version 1.7.1

**Comment by Slotherak** [comment]
Really? Citadel? That’s where the issue is? I am surprised because that dragon was a level 5 dragon, and it was nowhere near death yet (I had a Diamond sword, mind you, I was whittling it’s health down slowly but surely, and there’s no way in heck I managed to kill it within three minutes of sporadic slashing of a Diamond sword from silent gear. Those break faster than the vanilla variety). If that’s the case then I’ll let you know if that fixes everything. Would that also be affecting the JEI manaweaving recipe browser? I am not sure what citadel is or does, but it sounds like a base library mod (which could easily cause more problems if downgraded…).

**Comment by Slotherak** [comment]
Alrighty then! Got a crash report this time. Did not downgrade citadel yet, as I was trying to figure out what went wrong, and as I was logging back into the world, I somehow respawned underneath the dragon and during the laggy restart it managed to kill me. No surprise. Thank you gravestone mod. As far as the dragon dying part, that’s not the issue at all. It’s apparently (if I’m reading this crash report correctly) something to do with the dragon itself… but it’s not exactly clear. This time I was simply fleeing combat (after all, it took me from full health to zero in one hit, so I was getting the hell out of there pronto), and repositioning, as well as recrafting the Treasure Hunter charm that I had apparently not made at the time of the last save point before the disconnection. I had already made and equipped said charm, and got into my nook/cranny/one-block-wide-and-high-spot, to punish this dragon. And I had not even attacked it yet, because I was being distracted by some blob fish dying nearby and was trying to figure out why the magnet ring wasn’t picking them up (and more importantly why the dragon could clearly see me but was still trying to bug out, flip back and forth, crunched against the wall like some PlayStation 2 glitch). And then the game crashed (instead of disconnecting, which I was thankful for) and spat out this crash log.

Here is the log:
[Crash log pastebin.com (it’s always the dragons!)](pastebin.com/LCee9U6J)

**Comment by Slotherak** [comment]
From what I can tell, I think that the dragon itself is the actual problem so I’m just going to ditch attacking this one and find a different type of dragon to slay, see if that works. If not I’ll try to figure out how to downgrade a mod in the curse forge application.

update: server disconnected… this is getting annoying. Again, I’m playing on single player mode. As in completely on my computer in front of me singleplayer mode. At least I can still select the world I was just in. Let’s see how far back it kicks me…— nope. A crash without a log. Perfect. Alright, Google. Tell me how to use the curseforge system to revert a mod in a modpack to a previous version…

update, again: … why in the name of all that is holy is this not a default option? Seriously considering that modding is a very tedious and delicate process, and if the wrong option is added the whole thing is as useful as a screen door on a submarine, you would think that choosing which version of a mod to download would as default as choosing which modpack version to download. As well as excluding mods from modpacks. Maybe I have spent too much time away from Minecraft…

**Comment by Slotherak** [comment]
Alright. That seems to have solved the issue. Now why this had to be done… I have no clue. But thanks for the advice!
