### ISSUE TITLE
[Suggestion] Buffing The Refined Storage Controller

### ISSUE THREAD

**Issue by RyanP1991** [The-Nexus-Project/Limitless-3#226]
With a forever expanding reinfed storage the cost of maintaining it slowly increases. The controller currently can only hold 32,000 RF if the system requires even 32,001 RF to maintain the controller will forever lose power and will never be able to recover. Unlike AE where you can increase the power bufferr with more controllers. 

All I am suggesting is to slightly buff the internal storage for the controller for ever expanding networks.

**Comment by OveR1337XD** [comment]
Yeah that's a disadvantage of using refined storage its bad for late-game usage for automation and stuff.

**Comment by Gbergz** [comment]
Will maybe buff it for a future update. Thanks for the suggestion. 👍

**Comment by Gbergz** [comment]
This will be done for the v1.11.1 update.

**Comment by OveR1337XD** [comment]
Thanks and on what is gonna get increased maybe 256k ATM6 did the same?

**Comment by Gbergz** [comment]
112k
