### ISSUE TITLE
Single player freezes after teleporting to a village, then also freezes after restarting the game and loading the world.

### ISSUE THREAD

**Issue by alejandro-esquivel** [The-Nexus-Project/Limitless-3#227]
### Describe your issue, what happened?
After teleporting away using the /locate command to locate a village and teleporting to it, the game froze. I tried restarting the game and when I loaded it my character was still in the village and the server was still not responding.

### To Reproduce
1. type "/locate village" in the chat
2. click on the coordinates to teleport to them (if you have cheats enabled)
3. game server freezes after a minute

### Expected behavior
I was expecting the game not to freeze.

### Crash Reports & Logs (Don't paste entire crash reports here.)

https://gist.github.com/aleaallee/d6a012d94c96d5ddb85acbf5fc761ad9#file-latest-log

### Affected Version

- Pack Version: 1.10.9
- On a server?: No

**Comment by Gbergz** [comment]
Hey, late reply. Can't reproduce this issue at all. Also the logs are cut off due to the upload limit.
