### ISSUE TITLE
Silent Gear Saw Tool Crashing Server

### ISSUE THREAD

**Issue by yugiwill100** [The-Nexus-Project/Limitless-3#229]
### Describe your issue, what happened?
 Upon using a Saw from Silent Gear, made purely of cobblestone to cut down a tree, if its durability reaches zero/breaks the server crashes but client stays up.

### To Reproduce
Craft a Silent Gear Stone Saw with a normal tool rod.
Cut down a zelkova tree with low durability on the stone saw.
Severe should freeze, and after roughly thirty seconds to a minute produce crash log and stop kicking client to main menu.

### Expected behavior
Much like prior to durability reaching zero, it merely cut as much tree as possible then leave tree blob behind. NOT hard crash server.

### Screenshots
--

### Crash Reports & Logs (Don't paste entire crash reports here.)
http://hastebin.com/arimosavej.rb
[crash-2021-08-19_17.38.33-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/7017861/crash-2021-08-19_17.38.33-server.txt)

### Affected Version
- Pack Version: 1.10.9
- On a server?: LL3V1.10.9

**Comment by Gbergz** [comment]
https://github.com/SilentChaos512/Silent-Gear/issues

**Comment by yugiwill100** [comment]
Copy I see it now as issue #402 on their github. Thanks for linking. To any others experiencing similar issues it seeming is on mods side, not modpack.
