### ISSUE TITLE
Unable to open GUI of certain modded blocks

### ISSUE THREAD

**Issue by jayschuster** [The-Nexus-Project/Limitless-3#23]
### Describe your issue, what happened?
I cannot open the GUI of any block from Silent's Mechanisms and Expanded Storage (Might be more, those are the only mods i have gotten to in my stage of the game)

### To Reproduce
1. Place down any block from either Silent's Mechanisms or Expanded Storage.
2. Right click it.
3. Nothing happens.

### Expected behavior
The block to open the GUI and be functional.

### Screenshots

https://youtu.be/MBOCj1Ml474

### Crash Reports & Logs (Don't paste entire crash reports here.)
Not applicable

### Affected Version
- Pack Version: 1.6.4
- On a server?: Yes

**Comment by Gbergz** [comment]
Are you by any chance using optifine? If you do, please verify the issue without it.
