### ISSUE TITLE
Putting Filled Nether Pumice into a Heat Generator causes server crash

### ISSUE THREAD

**Issue by Tragiik** [The-Nexus-Project/Limitless-3#230]
### Describe your issue, what happened?
Running a server on version 1.10.9, after putting a Filled Nether Pumice block from Craft and Hunt into a Heat Generator from Mekanism causes server to crash. The server can reboot but crashes when a player in the same chunk as the Heat Generator joins.

### To Reproduce
1. Set up Heat Generator with 3 lava sources surrounding it
2. Put Filled Nether Pumice in Heat Generator's fuel slot
3. See error

### Expected behavior
Nether Filled Pumice is a fuel source so I figured it would work the same as putting fuel in the Heat Generator

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/tb8gCHUn

### Affected Version

- Pack Version: 1.10.9
- On a server?: Yes

**Comment by noncom** [comment]
According to the log it's Mekanism + Craft and Hunt interaction problem. This should be reported to one of them, ideally Mekanism should solve this since it's them who's crashing. If it still reproduces.
