### ISSUE TITLE
Crash after opening lootbag

### ISSUE THREAD

**Issue by Warzat66** [The-Nexus-Project/Limitless-3#231]
I open my lootbag like usual after quest and then when i open my inventory, the game crash

for the crash log -> https://pastebin.com/FwB54BFR

i'm on the version 1.10.9 soloplayer

**Comment by Gbergz** [comment]
You can use NBT Explorer and remove that item from your inventory if it continues to crash.

Look for. cb_microblock:microblock

I've blacklisted that item so it won't drop again. (For next update).

**Comment by Warzat66** [comment]
thank :)
