### ISSUE TITLE
aquaculture 2 treasure chests quest reward not able to open

### ISSUE THREAD

**Issue by wendictive** [The-Nexus-Project/Limitless-3#232]
the treasure chest rewarded from quests 

ive tried everything ..i cant open them ... right click left click shift click .. click into chest

its single player and fire and ice mod is  disabled.. donno if that can be the issue

**Comment by Gbergz** [comment]
If you disable Ice and Fire, those won't work since there's Ice and fire rewards in them.

**Comment by Gbergz** [comment]
you can edit out those values if you want in : `MODPACK\kubejs\data\aquaculture\loot_tables\box\treasure_chest.json`

**Comment by wendictive** [comment]
ty that worked

**Comment by Gbergz** [comment]
great!
