### ISSUE TITLE
Outer End Crashing on me whenever I access it.

### ISSUE THREAD

**Issue by Slotherak** [The-Nexus-Project/Limitless-3#233]
### Describe your issue, what happened?
So, I have discovered that about _one-third_ of the vanilla game is inaccessible. Specifically, the Outer End Islands. Every time I try to access the OEI, the game will invariably crash with either a server disconnect warning (on singleplayer mode, which is impressive...) or a silent, crash log-free shutdown. To be clear, the End is accessible. The main portion where the Ender Dragon is fought is completely navigatable. However the Outer End Islands are not, and that tells me that either something is horribly wrong with my seed's generation (which would mean starting over from scratch... again... without any guarantee of a fix) or there is a problem with one of the mods that affect the OEI. Dimensional dungeons? Works. Twilight forest? Works. Ratlantis? Works. Blue Skies? Works. Mining dimension? Works. Nether? Works. Overworld? Works. Main End? Works. BumbleZone? Works. Outer End Islands? Crash. Part of the vanilla game is _gone_, and while I don't exactly miss the original OEI, as it was pretty barren, I wanted to explore the various new biomes of the end and meet the new inhabitants (as well as get some TiC Ender Slimeballs, and Shulker casings, and Chorus Fruit, and possibly other OEI specific things like the Elytra, and the Dragon Skull). And I am not spamming loot boxes to get these (if they are even available through them, which I heavily doubt. Third playthrough and third time I've hit this stupid problem, I would have found said loot box reward by now, I would think).

### To Reproduce
1. Go to the End Dimension
2. Defeat Ender Dragon to generate OEI warp portal
3. Use OEI portal (I was being frugal with ender pearls and instead walked through while 'prone', but I doubt that that had anything to do with it)
4. See OEI briefly (if you are lucky, or game is that laggy)
5. See loading tips screen (my old nemesis... we meet again)
6. Get booted from single-player server (because that makes perfect sense) or Experience a "silent" crash.

### Expected behavior
Experience the outrageous Outer end Islands, cut down Bulbis trees, dig up interesting ores and rocks for building accents, ride on EnderGrades, lasso Spectres, collect Chorus flowers, raid End Cities, defeat the Void Worm... Lots of content to be found here, and I can't get to it... 

### Screenshots
Sorry. I can't screenshot the brief view of the OEI in the amount of time it takes the game to crash/disconnect.

### Crash Reports & Logs (Don't paste entire crash reports here.)
A silent crash produces no crash log, so I have nothing to go forward with here...

### Affected Version
- Pack Version: 1.10.7 (using citadel 1.7.1 per the previous issue)
- On a server?: Not that I'm aware of. If I am, then I get amazing connectivity to this server. It works without wifi...
Update: for those who have this exact problem, just update Better End (forge) to latest version.

**Comment by Slotherak** [comment]
Can't believe I didn't think to check the files for the crashlog. I'm apparently a huge idiot... attaching log link below.

[Pastebin link](https://pastebin.com/HQ5iAeRw)

**Comment by noncom** [comment]
This is a BetterEnd crash, should be reported to them.
