### ISSUE TITLE
craft conflict

### ISSUE THREAD

**Issue by Warzat66** [The-Nexus-Project/Limitless-3#234]
There is a craft conflit between the glass facade from "crossroads" and the mirror from "solar flux reborn".

i can't change the output with RFTools's crafter, applied or refined auto craft.

The only output available is the glass facade, so i can't auto craft solar panel

The craft : 
glass/   glass    /glass
  x   /iron ingot/   x
  x  /       x       /   x

**Comment by Gbergz** [comment]
Will get this fixed for next update, thanks for report. 👍 
Closing when update is out.

**Comment by Gbergz** [comment]
Fixed in v1.11.0
