### ISSUE TITLE
Crash when adding the Mod Immersive Railroading

### ISSUE THREAD

**Issue by MeeseGX** [The-Nexus-Project/Limitless-3#235]
I tryed to add a Mod (Immersive Railroading) and after that it allways Crashes when i enter a World.
I allready contacted the the Owner of the mod but they cant do anything with my crash report, they never saw that before.
So i thought maybe you can help me.
I really like this Modpack and i would like to have that mod in your Modpack, so i tryed to add it. I like Trains :D

To Reproduce
1.  Add the Mod Immersive Railroading with its needet mods (UniversalModCore,TrackAPI) into the mod folder.
2. Start it enter a World/Server.
3. Then it Crashes

Expected behavior
I can play the Pack with the Mod installed.
Crash Reports & Logs
I tryed diffrent mod versions
newest mod version:
[crash-2021-08-31_05.40.30-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/7102577/crash-2021-08-31_05.40.30-client.txt)

Affected Version
- Pack Version: 1.10.9
- On a server?: Yes and Singelplayer

**Comment by Gbergz** [comment]
This is probably due to OptiFine, I can see it in your logs. Try removing it then launch again. Also since the mod isn't in the pack I'll close this now.
