### ISSUE TITLE
Crashing on launching

### ISSUE THREAD

**Issue by lyssieth** [The-Nexus-Project/Limitless-3#237]
### Describe your issue, what happened?
When trying to launch TNP Limitless 3 via MultiMC, it just crashes after some time.

### To Reproduce
1. Install TNP Limitless 3 1.11.0 via MultiMC
2. Try to launch it

### Expected behavior
Launching as normal

### Crash Reports & Logs (Don't paste entire crash reports here.)
[Crash Report](https://paste.ee/p/QII6y)
[latest.log](https://paste.ee/p/v0CE1)

### Affected Version
- Pack Version: 1.11.0

**Comment by tayrayb** [comment]
You're running the wrong version of Java according to that log. You should be running Version 8 or 11. I use 11 personally and it works fine for me.

**Comment by Gbergz** [comment]
You're running Java 16. Use 8 (or 11), personally 8.

Java 16 is meant for 1.17 and above.

**Comment by lyssieth** [comment]
Dammit, I forgot. Apologies!
