### ISSUE TITLE
Feature Request: Craft-able Concrete recipe

### ISSUE THREAD

**Issue by BrettMoan** [The-Nexus-Project/Limitless-3#239]
In some other packs i've often seen a nice Quality of life 3x3 crafting recipe for concrete. that is just 8 concrete (of any single color) all around one of [ (water bucket), (mystical agriculture water essence), or (water-bee comb)]

it makes building with mass quantities of concrete easier for building cool bases :)

**Comment by Gbergz** [comment]
Might add this in a future update!
