### ISSUE TITLE
Wrong Mob Seed

### ISSUE THREAD

**Issue by Delor317** [The-Nexus-Project/Limitless-3#240]
### Describe your issue, what happened?
Mystical Agriculture mob seeds are creating the wrong seed. As an example I collected 4 jars of each chicken, cow, pig and sheep. I ended up with 4 chicken seeds only. The cow, pig, and sheep all gave chicken seed. I further tested other tiers i.e. imperium and got a similar result where i got the wrong mob seed when doing enderman. I got blaze instead.

### To Reproduce
1. Choose mob seed to get
2. Fill 4 soul jars with said mob soul
3. Arrange the 4 jars as well as appropriate tier essence and soulium seed
4. Active center and get wrong seed

### Expected behavior
I expected to get the mob seed of the mob inside the jar.

### Screenshots
Not sure how you want me to go about this part.

### Affected Version
- Pack Version: V. 1.11.0
- On a server?: Single Player

**Comment by BrettMoan** [comment]
### To Reproduce
I'm seeing the same thing. I grinded for skeleton jars for skeleton seeds and instead got blitz seeds. :( 

the recipes seem to ONLY be looking at the jar and not the contents, as even empty jars work.

I also tried the following EMPTY jars, and got the following seeds.

For each tier, you get one and only one type of seed, so apparently no randomness.

tier 2 = Chicken Seeds
tier 3 = Blitz Seeds
tier 4 = Blaze Seeds
tier 5 = Wither Skeleton Seeds

### Affected Version

- Pack Version: V. 1.11.0
- On a server?: Public NA server

**Comment by BrettMoan** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/issues/449 looks like it was fixed @Gbergz
