### ISSUE TITLE
Item equip sound (Band of Mana + Greatest Band of Aura)

### ISSUE THREAD

**Issue by CritonDE** [The-Nexus-Project/Limitless-3#241]
Modpack Version: 1.11.1
When I open my Inventory in any way (@RS, Backpack...) and the Band of Mana is in a bauble slot the sound "item.armor.equip_generic:minecraft" is constantly playing with an open inventory, because of the changing mana value.
If the Band of Mana is in the Inventory, there is no sound.

**Comment by Gbergz** [comment]
Could be caused by https://www.curseforge.com/minecraft/mc-mods/armor-sound-tweak, not sure though. But most likely.
