### ISSUE TITLE
Issues with iron chisel head & arcane crystal ore.

### ISSUE THREAD

**Issue by asppel** [The-Nexus-Project/Limitless-3#242]
TNP Limitless 3 1.16.5.
1. Iron chisel head recipe (KubeJS mod) conflicting with iron rod recipe (Immersive engineering).
2. Arcane crystal ore (Forbidden & Arcanus mod) texture is missing. The ore is completely transparent.

**Comment by Gbergz** [comment]
I'll fix this recipe conflict next update.

Now answering nr2. Do you have OptiFine or any other performance mod installed?
