### ISSUE TITLE
Zooming With Fn and Media keys

### ISSUE THREAD

**Issue by RubberDuckky** [The-Nexus-Project/Limitless-3#243]
*Using optifine*

Pressing the function key (Fn) and any F1-12 key will cause the game fps to dip and it will zoom in and pulse once or twice, and double pressing any of the F keys will cause it to stay zoomed in. pressing an F key will return view to normal.

All you have to do is press Function+F1-F12.

I dont think this is supposed to happen.

Modpack version 1.11.2 in a singleplayer world.

**Comment by Gbergz** [comment]
OptiFine. Can you reproduce this without OptiFine? There's already a zooming mod in the pack. X button by default. Could be that your key has been reset to another keybind. You can toggle zooming by double-clicking the zoom button. (SmoothFocus is the mod).
