### ISSUE TITLE
Mekanism bug

### ISSUE THREAD

**Issue by CrAzYfOrDaYs** [The-Nexus-Project/Limitless-3#244]
I'm not using optifine, there is a machine in game from mekanism called the rotary condensentrator that doesn't work properly it never produces like it should. if you put lithium liquid into it it never produces lithium gas.

### To Reproduce
put lithium liquid into the machine with power

### Expected behavior
produce lithium gas

### Affected Version
- Pack Version: 1.11.2
- On a server?: yes on my own

**Comment by MechanicalDragon0687** [comment]
are you making sure to set it to decondenstrate mode rather than condenstrate mode? it has 2 modes and requires you to toggle it to the other mode
