### ISSUE TITLE
Astral sorcery 

### ISSUE THREAD

**Issue by EduardoLatvia** [The-Nexus-Project/Limitless-3#245]
There is a problem with marble and rock crystals not spawning naturally.
I have tried to find rock crystals and marble spawning naturally. I tried using the digital miner from mekanism to find marble but i couldn't find any.

### Expected behavior
I expected some white beams coming out of the ground while holding the resonating wand but here werent any in a large radius.

### Affected Version
- Pack Version: 1.11.2
- On a server?: yes

**Comment by Gbergz** [comment]
Rock Crystal Ore not generating is caused by Extended Caves and that mod is being removed next update.

Astral Sorcery Marble worldgen is disabled on purpose and it's crafted simply by putting Quark Marble into a crafting grid.
