### ISSUE TITLE
Magnesium Crash

### ISSUE THREAD

**Issue by OveR1337XD** [The-Nexus-Project/Limitless-3#246]
I want to use a mod called Magnesium instead optfine but for some reason entering in world crash the game! Is there a way to make it work?

[2021-11-06-2.log](https://github.com/The-Nexus-Project/Limitless-3/files/7491787/2021-11-06-2.log)

**Comment by Gbergz** [comment]
Try removing the mod Roadrunner.

**Comment by OveR1337XD** [comment]
Same thing 🙁

**Comment by Gbergz** [comment]
Then I'm sorry. Probably won't work then.

**Comment by OveR1337XD** [comment]
Ok thanks for the help anyway!
