### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by Kingofstrike** [The-Nexus-Project/Limitless-3#25]
### Describe your issue, what happened?

Missing inventory textures armor iron  ( Purple/Black) 

### To Reproduce

Crafting gear right after start  with silent gear. 

### Expected behavior
Showing the rigt textures

### Affected Version

- Pack Version: 1.7.1b
- On a server?: No
- First modpack install
- New world

**Comment by Gbergz** [comment]
This is a Silent Gear issue, not much I can do about this unfortunately.
