### ISSUE TITLE
Magnesium issue

### ISSUE THREAD

**Issue by Oskal79** [The-Nexus-Project/Limitless-3#252]
### Describe your issue, what happened?
Ghost chunk of blocks in air with Magnesium.

### To Reproduce
1. Download and install Magnesium lastest version.
2. Create a new world and join them.
3. See problem.

### Expected behavior
This mod super optimize TPS and FPS, with optifine i have 120-200 FPS and big lag spikes, with Magnesium i have 400-500 FPS minimum lag spikes, i need this mod, i have AMD RX 6600 XT and he very bad works with OpenGL + i have 360Hz monitor.

### Screenshots
https://i.imgur.com/USswsYL.jpeg
https://i.imgur.com/8E1ym4K.jpeg

### Crash Reports & Logs (Don't paste entire crash reports here.)
Log so big, can't upload to any site,

### Affected Version
- Pack Version: [Limitless 3 - v1.11.10]
- On a server?: No

**Comment by Gbergz** [comment]
Can't see that this is an issue worth reporting on here since the pack doesn't even come with Magnesium.

Report it to them, or try the updated version called "Rubidium".

**Comment by Oskal79** [comment]
> Can't see that this is an issue worth reporting on here since the pack doesn't even come with Magnesium.
> 
> Report it to them, or try the updated version called "Rubidium".

On Magnesium CurseForge writed this - "This Mod is NOT and never will be compatible with Optifine or Halogen." and this ALL... He don't have list of incompatibility...

Rubidium? I'l trie this soon.

**Comment by Oskal79** [comment]
Same problem with rubidium, exactly the same.

**Comment by Gbergz** [comment]
Sounds like it isn't compatible then.

**Comment by Oskal79** [comment]
I play in ATM 6 with Magnesium and all fine, no ghost blocks or something bad...

**Comment by Gbergz** [comment]
You can't compare modpacks at all, all modpacks have different mods and those mods interact with "performance enhancing mods" completely different.

Obviously there's a mod in LL3 that Magnesium(Sodium) doesn't like.

**Comment by Oskal79** [comment]
Yeah, i know.

**Comment by Oskal79** [comment]
Hmm, i don't know where is a problem, i removed all "render / graphics" mods and no changes, may be problem in Forge version or something. I will try something tomorow.
