### ISSUE TITLE
Animated Textures Cause Massive Lag in JEI, Storage Drawers, Item Frames, Etc.

### ISSUE THREAD

**Issue by Bones3951** [The-Nexus-Project/Limitless-3#253]
### Describe your issue, what happened?
Animated Textures Cause Massive Lag in JEI, Storage Drawers, Item Frames, Etc.
The two friends that play this pack with me also experience this.

### To Reproduce
1) Look at any animated texture on an item; enchanted book, etc.
2) Lag like hell

### Expected behavior
1) My frames not to drop

### Screenshots
![image](https://user-images.githubusercontent.com/105124006/167265498-00ee086a-1936-4247-85f7-d5c14a9f988b.png)
![image](https://user-images.githubusercontent.com/105124006/167265501-9a05fc36-d31e-4473-ba49-d3ee9a63f203.png)
![image](https://user-images.githubusercontent.com/105124006/167265504-b65c4152-a539-4db4-8648-1a61ec7860da.png)
![image](https://user-images.githubusercontent.com/105124006/167265512-bb190155-f7f6-43d6-9386-a9f56ec09ec1.png)
(After Looking in JEI)
![image](https://user-images.githubusercontent.com/105124006/167265520-31082470-4c60-43a6-992c-40e71ce1f278.png)

### Affected Version
- Pack Version: 1.11.11
- On a server?: Yes, dedicated (no server-side lag, no ticks being skipped)

**Comment by Gbergz** [comment]
This is just how rendering tons of icons work, they'll drop your fps immensely depending on system. Not much you can do.

**Comment by Bones3951** [comment]
> This is just how rendering tons of icons work, they'll drop your fps immensely depending on system. Not much you can do.

I don't suppose there is anything like foamfix could do previously to disable the animations?

**Comment by Gbergz** [comment]
For JEI you can leave the page blank while not using it (search for something that doesn't exist) or toggle it off. 
And [Drawer FPS](https://www.curseforge.com/minecraft/mc-mods/drawerfps) mod can help with the icons on drawers by not rendering the icons while further away from them.

You can also try the mod [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) + [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) which are ports of Sodium & Iris.
Or try optifine, if it works.

**Comment by Bones3951** [comment]
Thank you for your suggestions, appreciated.
