### ISSUE TITLE
[Issue]: Crashes When Joining World

### ISSUE THREAD

**Issue by RConTRS** [The-Nexus-Project/Limitless-3#255]
### What happened?

Crashes Every Time I Join A World, Didn't Modify Anything In The Pack

### Pack Version

Version: 1.12.0

### Are you using OptiFine, Rubidium/Magnesium, or Oculus?, both?

- [ ] Using OptiFine
- [x] Using Rubidium/Magnesium
- [ ] Using Rubidium/Magnesium + Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
https://bytebin.lucko.me/QTymRldGeQ
```

**Comment by Gbergz** [comment]
You checked that you didn't use Sodium (one of the forge ports), but you are. Remove it. Try again.

**Comment by RConTRS** [comment]
it wasn't obvious for me at first, i checked for magnesium and found it, i deleted it and now everything works fine except low fps.
the issue is solved.
