### ISSUE TITLE
[Issue]: World never loads even after hours

### ISSUE THREAD

**Issue by mae332** [The-Nexus-Project/Limitless-3#256]
### What happened?

A bug happened! I tried to load the save I started a few days ago and it will not load. The pack opens just fine, I tried creating a new world and it works and loads, but the world I want to play in will not load, I left it on for it to load while I was gone for a few hours todsy and it was still loading when I came back! I have not modified anything at all, I dont even know how to modify stuff, im clueless :(

### Pack Version

Version: v1.15.0

### To Reproduce

1.open the modpack, try to load my world, wait for hours, nothing happens, I click furiously to purposefully crash the game cause it wont close.

### Are you using OptiFine, Rubidium/Magnesium, or Oculus?, both?

- [ ] Using OptiFine
- [ ] Using Rubidium/Magnesium
- [ ] Using Rubidium/Magnesium + Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
Minecraft Exit Code Error: exit code -805306369 but that is because i gotta force it to crash by furiously clicking because it will never crash and i cant close the window otherwise.
```

### Anything else to add?

Im clueless with modpacks, please send help :( thanks<3

**Comment by Gbergz** [comment]
Send latest.log 
Andcrashreport if there is one.

Check if you've allocated enough ram around 8gb or more etc. should be enough.

**Comment by mae332** [comment]
[latest.log](https://github.com/The-Nexus-Project/Limitless-3/files/11177825/latest.log)
 Here you go! And I had around 10gb allocated when that happened so that shouldn't be the problem! Thank you so much for your help!

**Comment by Gbergz** [comment]
Hm, alright. Try reinstalling the modpack, transfer your world to that instance.

Go into the world folder and remove the serverconfig folder.

Enter world, see if it works.

**Comment by mae332** [comment]
Okay I'm gonna go try that, I'll tell you if it works!

**Comment by mae332** [comment]
Omg it worked, thank you!

**Comment by Gbergz** [comment]
Awesome, glad it works!
