### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by JesusRS655** [The-Nexus-Project/Limitless-3#27]
I don't exactly know how to explain this, or how to demonstrate it... Every time that I get in the game, the world keeps resetting itself. I keep my inventory, but the terrain and machines are resetting to a previous state, with all machines moved or missing. For example, my Refined Storage system keeps disappearing, and I can't access it, but when I put the machines back where they were manually, all my items are back in the system. I think this is a very weird bug, and I don't know if it's happened to anyone else.

**Comment by Gbergz** [comment]
This is a vanilla bug, if you remove a mod that has world generation, the world will fail to save and those chunks will reset everytime.

If you updated from 0.x.x you can't play on a world on 1.x.x
