### ISSUE TITLE
The weird Exit Code 0 / Failed to find resource file is still there...

### ISSUE THREAD

**Issue by vcnickels** [The-Nexus-Project/Limitless-3#28]
### Describe your issue, what happened?
Twitch fails to find the Forge Client file on initial install/update.

Mod Author has a fix for a previous Forge version here: [Is Twitch not Launching the Modpack? Then read this!](https://github.com/The-Nexus-Project/Limitless-3/issues/1)

The new file is here https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.3-34.1.42/forge-1.16.3-34.1.42-installer.jar

**Comment by Gbergz** [comment]
Don’t use Twitch. It’s bad and only seems to causes problems.
Use MultiMC: https://multimc.org/#Download OR GD Launcher: https://gdevs.io/#downloadContainer

**Comment by vcnickels** [comment]
> Don’t use Twitch. It’s bad and only seems to causes problems.
> Use MultiMC: https://multimc.org/#Download OR GD Launcher: https://gdevs.io/#downloadContainer

I don't disagree but, for better or worse, it's how a ot of people tend to find Modpacks.  It's how I found yours.
