### ISSUE TITLE
Fairy Lights and Large Fluid Tanks incompatibility causing crashes.

### ISSUE THREAD

**Issue by RandomCanadian** [The-Nexus-Project/Limitless-3#36]
### Describe your issue, what happened?
Game crashes when a fluid tank from Large Fluid Tanks (FluidTanks in JEI) is placed down. This is due to an incompatibility with Fairy Lights.

### To Reproduce
Place down a FluidTanks tank and the game will crash.

Removing fairy lights will let you place it without a crash and allow you to re-enter any broken saves.

### Affected Version
- Pack Version: 1.7.4
- On a server?: On official server.

[crash-2020-11-16_22.02.48-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5551898/crash-2020-11-16_22.02.48-client.txt)

**Comment by noncom** [comment]
The issues were created by RandomCanadian.
For reference:
https://github.com/pau101/Fairy-Lights/issues/96
https://github.com/Kotori316/FluidTank/issues/64
