### ISSUE TITLE
Missing double dust recipes for silent mechanism's bauxite ore and zinc ore

### ISSUE THREAD

**Issue by GarthF** [The-Nexus-Project/Limitless-3#38]
### Describe your issue, what happened?
Missing double dust recipes for silent mechanism's bauxite ore and zinc ore in the Mekanism Enrichment Chamber and Thermal pulveriser. Not sure if this is by design, but platinum, bismuth and uranium added by the same mod all do have recipes.

### Expected behavior
Ability to get double dust via one of these two machines.

### Affected Version
- Pack Version: 1.7.5

**Comment by Gbergz** [comment]
I can add this if its needed. Thanks for the report!
