### ISSUE TITLE
Log over 100000 lines

### ISSUE THREAD

**Issue by Shang2Tai** [The-Nexus-Project/Limitless-3#4]
When I entered the underground dungeon with spiral stair between floors (dont know what mod adds it) i got fps drop, when i looked at logs there was this "MultiMC stopped watching the game logs because the log length exceeded 100,000 lines.
You might need to fix your mods as the game keeps writing logs to files and is probably wasting disk space at an alarming rate! "

Log was too big, so i upload it on my google drive:
https://drive.google.com/file/d/1pG9xZv3kU3ltWNbR5ZqV5LhP8O-rGjhA/view?usp=sharing

### Affected Version
- Pack Version: 0.9.2
- Single player

**Comment by Gbergz** [comment]
Yeah that is something the mod authors need to fix themselves, not much I can do about this unfortunately.

**Comment by Shang2Tai** [comment]
Can you find in log what mod cause problem?

Edit: Just second ago I found enderman spawner form Apotheosis mod, but where should be name of mob in Waila Overlay was ERROR.
