### ISSUE TITLE
Ender eyes not pointing to stronghold

### ISSUE THREAD

**Issue by InflamedSebi** [The-Nexus-Project/Limitless-3#40]
### Describe your issue, what happened?
we can't find the stronghold, since ender eyes always point north west now.

I needed to fix the nether and end like described in the guide, since it did removed them from level.dat when upgraded from 1.73a to 1.75 not sure if this is related.
It was working before the update.

### Affected Version
- Pack Version: 1.75
- On a server?: yes

**Comment by msmith-game-dev** [comment]
I have the same issue

**Comment by Atomibus** [comment]
same issue on a server with 1.8.2
