### ISSUE TITLE
Dungeon Crawl mod causing game/server hang/ crash (TEMP FIX)

### ISSUE THREAD

**Issue by RedTiger99** [The-Nexus-Project/Limitless-3#41]
Hi All.
Just letting everyone who might run into this problem.
There is problem with the current version of dungeon crawl (2.2.1), when the game tries to generate a dungeon it has a chance to hang your game (Both Solo world and Server)

My current fix is to roll back the mod version to 2.1.1, as the new/current version uses a slightly different generation method.
From the testing me and my friend have done on both solo and server there is no work around with the current version. 
If you get caught in that bad chunk you WILL have to roll back (If on server).

Hope this helps
-RedTiger

Affected Version
Pack Version: 1.7.5
On a server?: Server & Single player

**Comment by spike11302000** [comment]
I also can confirm this happens. I had my server crash when players went to a certain location. and noticed in debug.log the last thing to happen something to do with dungon crawl. XYROC/DungeonCrawl#51 XYROC/DungeonCrawl#42
