### ISSUE TITLE
Cyclic Experience Pylon doesn't store XP when sneaking on top of it

### ISSUE THREAD

**Issue by choekstr** [The-Nexus-Project/Limitless-3#43]
Using version 1.8.0 of the pack
Cyclic version 0.9.3

According to the description in JEI and the cyclic 1.16 issue tracker, the buttons have been deprecated and now the way to store XP is to sneak on top of the pylon.  I can't seem to get this to work and I have left an issue on the cyclic mod issue tracker but wanted to make others aware as well since this was a wasted craft for now.  There was just a new release of cyclic 3 days ago and I was hoping this would have been fixed but doesn't seem to be.

**Comment by mellamokb** [comment]
I found that it worked if you give it a redstone signal, but yeah in general it's pretty crappy solution because it is incredibly slow to drain or retrieve xp (plus requiring sugar to retrieve it). You would be much better off to use a Hero's Medallion.

**Comment by choekstr** [comment]
I think we can close this, the redstone signal seems to be the answer.
