### ISSUE TITLE
XP Block from Global XP mod doesn't store player experience when shift right-clicking as it's supposed to

### ISSUE THREAD

**Issue by choekstr** [The-Nexus-Project/Limitless-3#44]
Using version 1.8.0 of the pack
Global XP version 1.16.3-1.4.15

As the Cyclic Pylon has a bug and can't store player XP, I tried  the XP Block from Global XP mod and it doesn't store player experience either.  As this is the sole function of this mod (great mod btw), it might be a candidate for removal if others validate this isn't working; at least until it is fixed.  

FWIW, the reliquary Hero's Medallion does work to extract player XP and return it properly.  I had originally thought it might be my player that was bugged but I think it's just the early versions of the other two mods.

**Comment by Capt-efficiency** [comment]
I've been using the xp block from 1.7.5 until 1.8.0, I haven't had any issues with storing/retrieving xp. Maybe make a new one to see if that solves the issue?

**Comment by choekstr** [comment]
Just tested in a superflat new world and the XP block works, but it wasn't FTB Quest given experience; which is what I think might be the case.  I'll do some more testing and maybe move it to a non claimed chunk as well.

**Comment by choekstr** [comment]
EDIT: I just realized I didn't realize I had a shield equipped and it was causing the issue. Removed the shield and it worked again.
