### ISSUE TITLE
Optifine crashes game during load after updating to 1.8.0

### ISSUE THREAD

**Issue by JSchonblum** [The-Nexus-Project/Limitless-3#47]
Optifine worked previously on 1.7.5. Game now crashes during start up if optifine is enable with this error:

org.spongepowered.asm.mixin.transformer.throwables.mixintransformererror

**Comment by batteryhun78** [comment]
Had the same problem +1
Removing optifine has worked.

**Comment by billyty08** [comment]
As a general rule you should never post an issue for something you have added to the pack that was never intended

**Comment by mellamokb** [comment]
As another Optifine user, I would point out that you may have luck using OptiForge: https://www.curseforge.com/minecraft/mc-mods/optiforge. It attempts to more quickly bridge the gap between Optifine and newer releases of Forge.
