### ISSUE TITLE
Is it possible to add something for FTB Quests to allow teams?

### ISSUE THREAD

**Issue by msmith-game-dev** [The-Nexus-Project/Limitless-3#49]
Is it possible to add something for FTB Quests to allow teams? Currently at the top left I only see the FTB Quest and Claimed chunks icons but not the teams

**Comment by choekstr** [comment]
Read the description for the FTB Teams mod which is in the pack: [https://www.curseforge.com/minecraft/mc-mods/ftb-teams](https://www.curseforge.com/minecraft/mc-mods/ftb-teams )

**Comment by Gbergz** [comment]
``To create a team, use "/ftbteams create Name here". To change it's settings, use "/ftbteams settings <key> <value>", use tab to cycle through them. Team data is stored in world/data/ftbteams folder.``

**Comment by msmith-game-dev** [comment]
I mean I did do that but even if us being on the same team (confirmed using /ftbteams list and saw he was on the team, had to invite before hand) it still doesn't sync with the FTBQuests (although seems to work for FTBChunks)

**Comment by msmith-game-dev** [comment]
I just thought it was related to the fact the icon wasn't at the top left, figured that even if I used the command lines there was a broken dependency or something

**Comment by Gbergz** [comment]
Quests progress syncing in teams is currently not working. So just drop the items when one of you crafts it and you'll both progress.

**Comment by msmith-game-dev** [comment]
Thank @Gbergz yes indeed that's what we have been doing but it's a little tedious
