### ISSUE TITLE
Im getting an error 

### ISSUE THREAD

**Issue by Apwalchan** [The-Nexus-Project/Limitless-3#51]
TNP limitless 3 1.16.4
version 1.7.5
on cursed forge
every time i try and start the game is gives me this error in the screen shots

![Screenshot 2020-12-02 204340](https://user-images.githubusercontent.com/73681852/100956919-2d762180-34df-11eb-8b7f-78c1606277df.png)
![Screenshot 2020-12-02 204520](https://user-images.githubusercontent.com/73681852/100956989-51396780-34df-11eb-9ffc-90f1d7be063c.png)
![Screenshot 2020-12-02 204550](https://user-images.githubusercontent.com/73681852/100957049-68785500-34df-11eb-9900-c82829b793b3.png)

**Comment by Gbergz** [comment]
Try using

GD Launcher: https://gdevs.io/#downloadContainer 

or

MultiMC: https://multimc.org/#Download

**Comment by Gbergz** [comment]
And also you're profile says 1.8.0, but you're saying that you are using 1.7.5?
