### ISSUE TITLE
Nether World Gen issues and to much structures (Ice & Fire)

### ISSUE THREAD

**Issue by TheSnowyChickens** [The-Nexus-Project/Limitless-3#52]
### Describe your issue, what happened?
----- first issue -----
Every time we update the pack (and maybe random during one version) the nether world gen is ugly with "a new world seed" generation in a already existing world. (see the yellow marks on the screen)
------ second "issue" -----
I can find to many dragon hoards in the world and to many of the desert "dungeons" with these creepy creatures inside. ("tarantulas" or something like that)

### To Reproduce
1. Create a world
2. Create the Nether
3. Update the pack
4. Explore more of the nether
-----
1. Explore the world

### Expected behavior
No ugly chunk bugs

### Screenshots
![grafik](https://user-images.githubusercontent.com/29357962/100959594-ee67c080-351e-11eb-8760-b75812128e30.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
I can't give you some of that, because I play on a server.

### Affected Version
- Pack Version: 1.8.0
- On a server?: Yes

**Comment by Gbergz** [comment]
The ugly chunk borders are normal when you update a mod that effects world generation. Nothing you can do about it. Happens even in vanilla if something huge is changed.

And for the structures I can try to lower their generation chances next pack update.

**Comment by TheSnowyChickens** [comment]
Is it possible to blacklist some biomes for Ice & Fire structures ?
Because this desert dungeon can spawn in the trees from the "Tropical Fungal Forest".

![grafik](https://user-images.githubusercontent.com/29357962/101075450-51e70200-35a2-11eb-9950-3d632849229b.png)

&
Oh okay, then we need to regenerate the nether with every new update.^^

**Comment by TheSnowyChickens** [comment]
Hey again,
this following crash doesn't fit with my issue, but maybe it is useful for you. :D

log -> [crash-2020-12-03_22.03.58-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5643896/crash-2020-12-03_22.03.58-server.txt)

I tried to fight a boss mob from Apotheosis and even before I started the fight, the server crashed.
