### ISSUE TITLE
Please update AIOT Botania

### ISSUE THREAD

**Issue by geeee785** [The-Nexus-Project/Limitless-3#53]
There is a bug on the current version of AIOT Botania, aiotbotania-1.16.2-1.3.2.jar, that is preventing of using the Terrasteel AIOT while having Terrasteel armor on. aiotbotania-1.16.3-1.4.3.jar, fixes this issue.  Thank you

**Comment by Gbergz** [comment]
No need to open an issue regarding a mod update. 
I always update mods every update if it doesn't break something ofcourse- Thanks for the report though.
