### ISSUE TITLE
Pneumatic Craft client crash with unknown cause.

### ISSUE THREAD

**Issue by RandomCanadian** [The-Nexus-Project/Limitless-3#57]
### Describe your issue, what happened?
If you turn on the "hackable block tracker" on the Pneumatic craft helmet on the official server it'll crash you. You can go into single player to turn it off to be able to rejoin. I'm unable to determine the block that causes the crash in single player.

### To Reproduce
Turn on the "hackable blocks" overlay at -297,71,-89 on the official server.

### Expected behaviour
An overlay of blocks defined as "hackable" by the mod.

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/gAj6uqfu

### Affected Version
- Pack Version: 1.8.0
- On a server?: Official

**Comment by Gbergz** [comment]
Try reporting this to the mod author of PneumaticCraft instead.
https://github.com/TeamPneumatic/pnc-repressurized/issues
