### ISSUE TITLE
Mystical Agriculture Essence Block Duplication

### ISSUE THREAD

**Issue by Quantium3** [The-Nexus-Project/Limitless-3#58]
Describe your issue, what happened?
If you craft essence in Mystical Agriculture using blocks, you can double imperium, superium, and insanium

To Reproduce
1. Craft 4 imperium blocks
2. Craft them into superium using the master infusion crystal
3. Craft the superium blocks into 9 superium
4. Craft each superium into 8 imperium
5. Craft the imperium into blocks, you now have 8

Expected behaviour
Should craft Imperium through insanium using 8 blocks instead of 4

### Affected Version
- Pack Version: 1.8.1
- On a server?: No

**Comment by Gbergz** [comment]
Probably a miss on my part. Didn't even know you can craft essence blocks with the crystal just regular essence. I'll be sure to get that fixed.

**Comment by Gbergz** [comment]
Fixed for next release, thanks for the report.
