### ISSUE TITLE
Game crashing randomly

### ISSUE THREAD

**Issue by ecfuguetero** [The-Nexus-Project/Limitless-3#59]
### Describe your issue, what happened?
Me and my friend have been playing in this modpack for about 50 hours now, in the beginning it was normal but after a certain point (I don't know when, I didn't notice any strange behavior after I crafted or placed any machine) it just crashed randomly, sometimes it was only his game, other was only mine, sometimes both, sometimes it crashed when I was flying with the mekanism jetpack so I stopped using it, then it crashed when went mining (breaking any block in general) so I stopped, and now it crashes even when I'm walking. The only mod I went I depth with was mekanism and AE2, the others I barely messed with.
my pc: ryzen 5 3600x, gtx 1060 6gb gigabyte, 16gb ram

### To Reproduce
play the game (and focus on mekanism? I tried to narrow it down but after a few hours I gave up)

### Expected behavior
no random crash

### Crash Reports & Logs (Don't paste entire crash reports here.)
[crash-2020-12-23_16.24.13-server.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5736857/crash-2020-12-23_16.24.13-server.txt)

### Affected Version
- Pack Version: 1.8.2
- On a server?: local server

**Comment by have-a-boy** [comment]
I've also had crashes related to the Mekanism jetpack, although I'm guessing the crash you reported here is not the same. As you can see I've created an issue on the Mekanism github, linking back to this one.
