### ISSUE TITLE
Can't craft QuantumStorage Unit or Entangled Block

### ISSUE THREAD

**Issue by processq** [The-Nexus-Project/Limitless-3#6]
### Describe your issue, what happened?
QuantumStorage Unit or Entangled Block cannot be crafted. None of the craftable chests can be used to craft these items.

### To Reproduce
Attempt to craft either one of the mentioned items with any chests.

### Expected behavior
Craft mentioned items.

### Affected Version
- Pack Version: 0.9.3
- On a server?: no

**Comment by Gbergz** [comment]
I'll be sure to get this fixed! Thanks for the report.
