### ISSUE TITLE
[1.16.4] Removing Apotheosis - A Suggestion

### ISSUE THREAD

**Issue by MokahTGS** [The-Nexus-Project/Limitless-3#60]
We have been running TNP3 for several versions now on a private server.  Throughout that time we have gotten random crashes, startup crashes, weird mob generation crashes...all tied to the Apotheosis mod.

We opted to remove the mod from the pack on our server and I'd make the case that it be officially removed until the crashes can be figured out.  While I like the mod, it doesn't seem to add anything vital that we can't live without.

**Comment by jayschuster** [comment]
Official server doesn't crash with it, and it adds tons of really fun enchantments / mobs. Downvote

**Comment by MokahTGS** [comment]
While I'd love to keep it, we haven't had a problem since removing it.

**Comment by Gbergz** [comment]
@MokahTGS I’ll keep this suggestion in mind. Because Apotheosis have caused issue in the past. And still do sometimes.

**Comment by MokahTGS** [comment]
My preference would be to fix the issue if we can figure it out.  The issue seems to be with either mod interaction or something on how Apotheosis is doing things.

The crashes that I've seen reported to them come back with a "will not fix" kind of answer.
