### ISSUE TITLE
[Suggestion] Ore unification - one way or another

### ISSUE THREAD

**Issue by Linguardium** [The-Nexus-Project/Limitless-3#63]
Currently i am seeing many of the same ores (same ore tag) from different mods, this fills inventories unnecessarily. What I have done locally (which is the easiest way) is to create recipes via datapack that take the ore tags, and spit out a specific version of the ore. 
This is not the ideal solution. Ideally, you could use something like https://www.curseforge.com/minecraft/mc-mods/emendatus-enigmatica to unify the ore blocks.  
As it stands, this modpack reminds me of many unfinished packs which lack oregen balance and such. It would be nice to only have 1 type of copper/tin/silver/etc.

**Comment by Gbergz** [comment]
What do you mean? There is only 1 ore for every ore type. Any other ore is disabled. Along with that theres alot of unification scripts in place.

**Comment by Gbergz** [comment]
> As it stands, this modpack reminds me of many unfinished packs which lack oregen balance and such. It would be nice to only have 1 type of copper/tin/silver/etc.

There is only 1 type of every ore. That is of you didnt mess with anything.

**Comment by Linguardium** [comment]
Odd, i was getting Crossroads ore gen as well as some thermal ore gen. There was 1 more mod's ores (dont know if thermal and the other overlapped, but crossroads definitely did). Perhaps the world generated incorrectly with default settings. 

As i look at the configs, they clearly say false, but i absolutely saw Crossroads tin generating. (dont have seed anymore as i was seed hunting for a good one). If i find this issue again i will open an issue with the mod then. 
Sorry for the trouble.

**Comment by Gbergz** [comment]
Thermal Ore is the Main Ore generation. As for Zinc that is from Silents as Thermal doesn't have a ore for that.

And no problem. I was just a little confused.

**Comment by Linguardium** [comment]
still getting crossroads oregen, at least. 
Crossroads seems like it should work as it doesnt register the feature to the biome if the config value is set https://github.com/Da-Technomancer/Crossroads/blob/4d3123e005442caf35c56a7334602fbbe823ce79/src/main/java/com/Da_Technomancer/crossroads/world/CRWorldGen.java#L53

https://snipboard.io/LHXdeV.jpg
https://snipboard.io/FLXGMC.jpg

The log file is rather large but i dont see any crossroads specific message in it other than the server toml being corrected for some reason
`[00:57:49] [modloading-worker-0/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file D:\_gdl\instances\TNP Limitless 3\config\crossroads-server.toml is not correct. Correcting`

edit: upon inspection the corrected server config toml has the correct false values as well.

The only change i made to the pack was to add xaero's minimap and world map which dont touch generation at all (and I also disabled the FTB chunks minimap & waypoints in-game)
