### ISSUE TITLE
Crash associated with Mekanism jetpack (ClassCastException) but caused by a mod that vanishes chestplates

### ISSUE THREAD

**Issue by have-a-boy** [The-Nexus-Project/Limitless-3#64]
### Describe your issue, what happened?
Minecraft freezes, then [crashes](https://gist.github.com/have-a-boy/abadb2b6676b3dd9cb35bf2bbc5f47e7) completely after flying around with the Mekanism jetpack. Someone described a similar situation in this [issue](https://github.com/The-Nexus-Project/Limitless-3/issues/59) but provided a crash report for a different problem. This happens seemingly at random, sometimes immediately after launch, sometimes after flying around for minutes, but always when the jetpack is currently in use and consuming hydrogen.

On every tick that the jetpack is actively used, Mekanism tries to cast the currently equipped chest armor to `ItemMekaSuitArmor` to consume hydrogen, only to find `AirItem`. I already [reported this](https://github.com/mekanism/Mekanism/issues/6815) on the Mekanism GitHub, but as the author pointed out to me, this shouldn't ever happen without some strange outside interference from another mod. I took a look at the code in question and Mekanism *does* check beforehand, that the slot is not empty and contains a jetpack.

I've since switched out my jetpack for a vanilla iron armor chestplate and I noticed that at random intervals my armor rating will flicker between my armor value with and without chestplate. So some mod, somehow is randomly removing chestplates for a about a single tick for no apparent reason 😕 . I have no idea what mod that could be, so hopefully someone else has an idea. 

### To Reproduce
1. Equip Mekanism hydrogen-powered jetpack
2. Fly around and hope the crash triggers

### Expected behavior
Chestplates not being randomly removed and Mekanism not crashing because of it.

### Crash Reports & Logs (Don't paste entire crash reports here.)
- [Crash log](https://gist.github.com/have-a-boy/abadb2b6676b3dd9cb35bf2bbc5f47e7)

### Affected Version
- Pack Version: 1.8.2 (playing in singleplayer)

**Comment by have-a-boy** [comment]
After some further research, even though it seems strange, I suspect that Iron Jetpacks causes this issue. A crash report someone submitted in a [comment](https://www.curseforge.com/minecraft/mc-mods/solar-helmet?comment=1) on a different mod seemed familiar, so I narrowed the list of potential conflicts down to the few that are shared between his modlist and the Limitless pack.

I disabled each of those mods one by one and tested for a few minutes using my jetpack constantly and paying attention to my armor rating. Since I disabled Iron Jetpacks, the issue hasn't appeared again in about four hours of active gameplay. It might be a coincidence, so I'll report back if it crashes again.

**Comment by Gbergz** [comment]
Any news regarding this? Is this still happening?

**Comment by have-a-boy** [comment]
Sorry, for the late update. I was busy with work. It seems this issue is still happening. I wasn't able to test version 1.9.3 yet but it does still happen up to 1.9.2. at least. I've now filed a bug report for IronJetpacks to hopefully nail down this weird issue, so you don't need to reopen this imho.
