### ISSUE TITLE
Duplication with Mahou Tsukai bow of weapon projectiles

### ISSUE THREAD

**Issue by Xplodin** [The-Nexus-Project/Limitless-3#65]
### Describe your issue, what happened?

It dupes swords/tools
### To Reproduce
1, get a dank (dank null thing)
2, get the bow of weapon projectiles
3, turn dank to pickup all
3, put desired tool in offhand,
4, shoot weapon near feet
dank collects the items and the bow runs infinite ammo somehow
its a little iffy but it worked when it wanted to

### Expected behavior
To shoot the sword/tool but not dupe it

### Affected Version

- Pack Version: 1.8.2
- On a server?: yes, official, i deleted any dupes btw.

**Comment by Gbergz** [comment]
Hm. Not sure this is something I can fix myself, but you could try reporting it to the mod author.
