### ISSUE TITLE
Game Lag when you go too far

### ISSUE THREAD

**Issue by Alex1324tg21** [The-Nexus-Project/Limitless-3#66]
When you go a bit far, about 2000 blocks the game remains as stopped, I can keep moving but I cannot do any action, when I mine something it does not give me the block or when I open a chest it does not open and the mobs are stopped.

My PC: I7-8700K  16GB -RAM  RTX2070

**Comment by ThatDeathKnight** [comment]
I'm having the same problem, haven't connected it to being far from spawn but that might be my issue too. I noticed the problem when I went to the end, but it continued when I came back to my base

**Comment by Gbergz** [comment]
Try installing the mod **Performant**.
https://www.curseforge.com/minecraft/mc-mods/performant/files/3148027
That file specifically
It's going to be included next pack update but you might aswell install it now.
Works client & server and it really helps with tps and to stabilize things.

**Comment by ThatDeathKnight** [comment]
The pack just doesn't load when added to the mods folder. Unsure why. It just says Exception in thread "main" when the error log shows on GDLauncher. Last thing it shows loading is Chissel And Bits

**Comment by Alex1324tg21** [comment]
> Try installing the mod **Performant**.
> https://www.curseforge.com/minecraft/mc-mods/performant/files/3148027
> That file specifically
> It's going to be included next pack update but you might aswell install it now.
> Works client & server and it really helps with tps and to stabilize things.

When I add the mod to the folder, minecraft crashes on startup

**Comment by Gbergz** [comment]
@Alex1324tg21 The latest file crashes the game. You need the exact file I sent you.
https://www.curseforge.com/minecraft/mc-mods/performant/files/3148027
Or just try the latest, it might've been fixed. Haven't tried.

**Comment by ituitis20-seferoglu19** [comment]
It still lags when you are far out any solutions?

**Comment by ozgur3512** [comment]
It still lags when you go far out. Any solutions?

**Comment by Gbergz** [comment]
Apparently this is caused by Ice and Fire. We will just have to wait until that update is out.

**Comment by Gbergz** [comment]
That update is out & the pack will release an update soon.
