### ISSUE TITLE
server crash on startup due to productivebees (v1.8.2) 

### ISSUE THREAD

**Issue by supremedutchgamer** [The-Nexus-Project/Limitless-3#67]
server crash on startup using currently newest (v1.8.2) server files on an AMD a10 7800, fresh win8.1 install, 12gb ram. 

[crash-2020-12-29_11.29.39-fml.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5750592/crash-2020-12-29_11.29.39-fml.txt)

[2020-12-29-5.log](https://github.com/The-Nexus-Project/Limitless-3/files/5750599/2020-12-29-5.log)

`java.lang.IllegalStateException: Point of interest types beehive and draconic_nest both list Block{productivebees:dragon_egg_hive}[expanded=right,facing=west,honey_level=1] in their blockstates, this is not allowed. Blockstates can only have one point of interest type each.
`

this part of the log suggests the issue is productivebees, removing this mod allows the server to start without issues.

**Comment by Gbergz** [comment]
For some reason you have updated Forge which for some reason breaks productive bees. 
The downloadable server files are using``forge-1.16.4-35.1.13.jar`` and you have **forge-1.16.4-35.1.28.jar**. 
Please don't modify the pack then report it as not working.
Try using the forge version the server-pack provided.

**Comment by JaisDK** [comment]
A new version of PB is up with a fix for the new Forge version.
