### ISSUE TITLE
Garden Cloche crop support

### ISSUE THREAD

**Issue by Linguardium** [The-Nexus-Project/Limitless-3#69]
I may have missed something, but it looks like Pam's crops don't work in the IE garden cloche. The garden cloche supports recipes but it appears kubejs doesnt have these there either. Is this intended to drive people away from the cloche? if not, is there work being done to add the crops to the cloche?

Locally i have generated recipes from the Pam's and simplefarming's loot tables, but I thought maybe I missed something or that there was work already being done so i wanted to ask.

**Comment by Gbergz** [comment]
Support for Mystical Agriculture crops in a Garden Cloche is coming next update. Might look into adding support for Pam's but it's not a priority right now.

**Comment by Linguardium** [comment]
if you want to test some of my changes, this was all auto generated based on mean average of drops assuming binomial distribution without fortune. i used a special case for pam's to use the seed rather than the crop and simplefarming to use the main global drop as the seed (seems to be the pattern they used). as such, some tweaking and testing is probably in order. I also assumed a time of 800 (which is the standard length of IE cloche crops with a few exceptions for shorter growth things and wheat for some reason).
[cloche.zip](https://github.com/The-Nexus-Project/Limitless-3/files/5755577/cloche.zip)

**Comment by Gbergz** [comment]
@Linguardium Just tried the datapack, seems like some items in both pamhc2 & simplefarming doesn't have the correct output. Some of them only give seeds. And like all pams give double the output. While they should only give 2 of the item and 1 of the seed. 

Other than that it looks great.
And If that can get fixed I'll include it! :)

**Comment by Linguardium** [comment]
Pams crops dont drop seeds unless they arent mature, so this made sense. Also, her loot tables have 2 separate pools that are rolled 1-3 drops of the crop if mature. So its not doubled, its just 2 for each pool (technically could be combined, not sure why she did it that way) 
In actual testing, i was getting an average of 5 per harvest of each crop
