### ISSUE TITLE
Broken Textures on Items

### ISSUE THREAD

**Issue by MokahTGS** [The-Nexus-Project/Limitless-3#7]
I'm seeing numerous broken textures for various books, armor and other misc. mod bits.

So far I've seen broken textures for some Silent Gear upgrades (Diamond tip upgrade), Craft & Hunt Book, Mana Gear armor (all pieces), several other tools from various mods.

There doesn't seem to be rhyme or reason for them.  I did see that the modpack is using a lot of resource packs that could be messing things up.

**Comment by Gbergz** [comment]
Patchouli issue.

**Comment by Gbergz** [comment]
Correction:
I think it's a Forge issue, it'll be fixed eventually.
