### ISSUE TITLE
Item duplication with Tetra workbench

### ISSUE THREAD

**Issue by Jastyo** [The-Nexus-Project/Limitless-3#70]
### Describe your issue, what happened?
It can duplicate any item or stacks.

### To Reproduce
1. Create the Tetra workbench.
2. Place an item into the slot.
3. Press the grave key and it will duplicate item/items from your inventory.

### Expected behavior
No duplication ;)

https://user-images.githubusercontent.com/76795117/103386063-f6525a80-4af4-11eb-9bf4-e80ba6120b28.mp4

### Affected Version

- Pack Version: 1.8.2
- On a server?: It duplicates on my server and the official server.

**Comment by Gbergz** [comment]
Just tried to replicate this indev and I can't. So it's _probably_ fixed next pack update.

**Comment by Gbergz** [comment]
Nevermind, it's reproducable. Can you check if it's reproducable with only Tetra?

**Comment by Jastyo** [comment]
I couldn't reproduce it with Tetra alone.

**Comment by Gbergz** [comment]
Seems like this is an issue with Tetra & Inventory Tweaks Renewed.

**Comment by Gbergz** [comment]
Mind posting this on Tetras issue tracker?

**Comment by Jastyo** [comment]
No problem, leave it with me.

**Comment by Gbergz** [comment]
Might not get fixed since its an issue with Inventory Tweaks Renewed technically, but we'll see.

**Comment by Gbergz** [comment]
I disabled that container in the InvTweaks config. Fixed next update.
