### ISSUE TITLE
Unsupported Mob type for Tempt Goal

### ISSUE THREAD

**Issue by hahapotatoes** [The-Nexus-Project/Limitless-3#72]
Not using Optifine and just have default files for client and server side.

### What happens
When exploring around the map or going from one place to another, the server crashes randomly. The lastest crash was when I (haha_potatoes) was looking up a recipe while I was in my farm area and my friend (Belarun) was beginning to explore a swamp when the server crashed and my client ended up crashing while Belarun's client didn't crash. 

Belarun tried to log in after setting the server back up and it immediately crashed. I went into his files with NBT explorer and set his coords to my location and my friends and I just learn to avoid certain areas.  

### Possible Replicate but Crashes Player
My guess is that something from apothesis mobs picking up simple farming items? We haven't been able to replicate it since it crashes whenever the chunk is loaded. 

### Expected behavior
Being able to explore the world without having to avoid certain areas due to crashes.

### Screenshots
![image](https://user-images.githubusercontent.com/49716468/103468873-5b32ce00-4d0a-11eb-948c-89b21edcb643.png)

![image](https://user-images.githubusercontent.com/49716468/103470141-c84e5f80-4d1a-11eb-8079-a3ece0cb0e27.png)

### Crash Reports & Logs
https://paste.ee/p/SgkI1 

### Affected Version
- Pack Version: Limitless 3 - v1.8.2 - release
- On a server?: yes, private server

**Comment by Gbergz** [comment]
Is this still happening? Can you try on 1.9.0? Re-open if needed.
