### ISSUE TITLE
Cant connect to server (Disconnected)

### ISSUE THREAD

**Issue by TheButterbrotMan** [The-Nexus-Project/Limitless-3#76]
### Describe your issue, what happened?
I cant connect to my server, i get disconnected, in server logs is a log. I can connect to offically server.

### To Reproduce

1. Setup 1.8.3 Server 
3. Start 1.8.3 Client
4. Connect to Server, get disconnect message.

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://pastebin.com/pQWDqCcx
### Affected Version
- Pack Version: 1.8.3a
- On a server?: 1.8.3a

**Comment by Gbergz** [comment]
You're not using the latest version on the Client or Server.

See:

```[13:06:18] [Netty Server IO #4/ERROR] [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [fairylights:net,ironshulkerbox:main_channel,pandoras_creatures:net,curiousshulkerboxes:main,craftingcraft:network] rejected their client side version number```

All of the mods listed above was removed in 1.8.3.

**Comment by TheButterbrotMan** [comment]
So i downloaded again the 1.8.3 serverpack on the server, and installed 1.8.3 on client, but i still get this error. I still can join on offically server.

I definitevely downloaded the right Packs.

Client shows 1.8.3 and Serverpack shows 1.8.3 MOTD.

If you want to test here is the ServerIP: 45.157.179.242

**Comment by Gbergz** [comment]
Can't be the right server files you downloaded then. It shows you have Pandoras Creatures and all the other mods that were removed in 1.8.3.

This is the latest Server pack : https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3157561

Edit: and it does not contain any of the removed mods. As I just redownloaded it to be sure.

Edit 2: Seems like you've still got Endergetic from 1.8.3 update so it feels like you've shuffled the mods from 1.8.2 & 1.8.3.

**Comment by Gbergz** [comment]
The best thing to do is just do a clean install of the server & client. 
Transfer the ``world`` folder & the ``maessentials`` folder from the previous server. (delete the existing maessentials in the newest server files, and replace with the old one.)

**Comment by TheButterbrotMan** [comment]
It is exactly the file i downloaded. In the mods folder of the server i dont have Pandora, Fairy, Curious and Craftingcraft.

I did only transfer the worlds folder, and did also a clean install.

EDIT: I updated from version 1.8.2, i deleted /serverconfigs also. Do i need to start the server with the 1.8.3 update before loading 1.8.3a?

**Comment by Gbergz** [comment]
Then that doesn't explain why you still have Pandoras Creatures, fairy lights etc on the server. They are there. While they arent if you downloaded the right file.
Edit: 1.8.3 & 1.8.3a is technically the same just some config changes. No mods removed, updated or added.

Edit 2: The server you sent to me when I pinged it did have Pandoras Creatures, Fairy lights etc installed.

**Comment by TheButterbrotMan** [comment]
The only thing i migrated is a 1.8.2 /worlds folder (without serverconfigs), in the new 1.8.3a Serverpack.

I uploaded world folder here: https://we.tl/t-PeQGgDzuTA

I will try again to install a clean server with this world. I really dont know, what i did wrong.

EDIT: I think i found issue. I use a server wrapper, that automatically use the old Backup folder. I thougth i can simple copy old folder, do it in new folder and use old folder for new server. But the wrapper automatically link TNP-Server to new Folder. 

Anyway thanks for your help.
