### ISSUE TITLE
Silent mechanic Coal Generator

### ISSUE THREAD

**Issue by ozgur3512** [The-Nexus-Project/Limitless-3#77]
### Describe your issue, what happened?
When you craft coal generator from silent mechanic and place it game crashes

### To Reproduce

crafted it
placed it and game crashed

### Affected Version

- Pack Version: 
- On a server?:

**Comment by ericlyonshansen** [comment]
Yes, I had the same exact issue. I'm running it single player on my desktop (not a server) using the CurseForge launcher. No other mods, data packs, resource packs, or shader packs installed.

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-3/issues/77

**Comment by Docdra** [comment]
Was an issue a few versions ago and is still an issue in the latest version (1.8.5a) as of this date - doesn't matter if playing SP or MP on a server, still crashes either way.
