### ISSUE TITLE
Armor Duplication

### ISSUE THREAD

**Issue by GordonLuce** [The-Nexus-Project/Limitless-3#78]
If you right click a piece of armor in a chest, it will sacrifice an item in your inventory and duplicate the piece of armor. I saved and quit, then crashed.

To Reproduce
1. Go to a chest
2. Put a piece of armor in the chest
3. Equip another corresponding piece of armor 
4. Right click on the piece of armor in the chest
5. Repeat

 Expected behavior
After several times, there should be multiple pieces of armor in the chest and some items in the player's inventory should be missing 

### Screenshots
I see no use for screenshots

### Crash Reports & Logs (Don't paste entire crash reports here.)
The crash reports showed nothing useful

### Affected Version
- Pack Version: v1.8.3a
- On a server?: no

**Comment by SkuxxDeluxe** [comment]
Pretty sure this is a visual glitch. Used to get this in FTB Ultimate.
If you log out and in, does it update (i.e. no dupes and items are back?)

**Comment by Gbergz** [comment]
@GordonLuce Can you confirm this isn't a visual glitch?
