### ISSUE TITLE
Refined Storage drive loss

### ISSUE THREAD

**Issue by Talidorn** [The-Nexus-Project/Limitless-3#79]
### Describe your issue, what happened?
Refined storage on a server (not the one hosted by y'all) loses Refined storage drives after a crash.  This is a known issue with Refined 1.9.10 and is fixed (reportedly) in 1.9.11.  Please include the update on your next release.

### To Reproduce
Run server, have a crash, lose drives in RS.
Please see https://www.curseforge.com/minecraft/mc-mods/refined-storage/files version 1.9.11 changelog for the known issue and fix.

### Expected behavior
No drive loss

### Screenshots
None

### Crash Reports & Logs (Don't paste entire crash reports here.)
Not sharing at this time.

### Affected Version
- Pack Version: 1.8.3a 
- On a server?: Yes

**Comment by Gbergz** [comment]
Fixed.
Update to pack version 1.8.4
