### ISSUE TITLE
Treated Wood Recipe Does Not Work - KubeJS problem?

### ISSUE THREAD

**Issue by MokahTGS** [The-Nexus-Project/Limitless-3#8]
### Describe your issue, what happened?
There doesn't seem to be a way to make treated wood in the pack.  The recipe with Creosote and wood planks is not there.

### Screenshots

https://www.dropbox.com/s/qaplyhbagml649x/2020-10-15_16.19.18.png?dl=0

### Affected Version
- Pack Version: 1.4.0
- On a server?: Yes

**Comment by Gbergz** [comment]
Wow what timing, I was just making this right now in my playthrough. And it is working for me. How strange.. 

hm..

**Comment by Gbergz** [comment]
Just tried it again in a new world, can't reproduce the issue.

**Comment by MokahTGS** [comment]
Odd is it this issue?

https://github.com/BluSunrize/ImmersiveEngineering/issues/4277
