### ISSUE TITLE
Crops not growing and farmland never gets wet no matter how much water is around the dirt block.

### ISSUE THREAD

**Issue by alexdk** [The-Nexus-Project/Limitless-3#81]
I don't know if I'm doing something wrong or not. 
I've tried to plant underground and aboveground nothing grows, even the farmlands in generated towns arent growing

**Comment by Docdra** [comment]
Having this same issue - only fix is to put a growth accelerator under the farmland, but this shouldn't be the case.

**Comment by choekstr** [comment]
This is a known issue and discussed/asked about every hour on the discord and so is a pinned message:

> Crops not growing? Read:
> 
> Edit: Updating Performant to the latest version will also fix the issue without having to change the config.
> 
> Alternatively if you dont feel like updating the mod (which is easy), you can do the following:
> #Enable fast chunk block ticks, reduces lag on random block ticks in the world but keeps the same growth e.g. on crops. default = true
> fastChunkBlocks = true
> 
> Change from true to false. In the "performant-common.toml" config file. And it'll be fixed.

**Comment by Gbergz** [comment]
this is fixed next update.
