### ISSUE TITLE
Modpack keep freezing without reason

### ISSUE THREAD

**Issue by MicaBloodless** [The-Nexus-Project/Limitless-3#82]
So, i play on the modpack for a time now.

Those last days, the game keep freezing and get stuck randomly without (To my eyes) any specific reasons. I got to restart the game completly to continue.

So this was already a pain to play on but today i can officially start a new save cause my original safe got stuck at the precise moment where i keep freezing, so if i load this save, it crash almost instant. Only an update can maybe save it, but i don't think it can.

Can you guys fix it ? At least to erase this problem for other players before they get the same issue.

**Comment by Gbergz** [comment]
Can you try updating Ice and Fire and see if this "freezing" problem goes away? It's a world deadlock and ice and fire had some. Supposedly fixed with their latest update. Give it a try and try the old world.

**Comment by MicaBloodless** [comment]
I may have found where the issue come from, it's crash/freeze when a witch throw a specific potion, i can't know which one, but i found out it was potion at least.
