### ISSUE TITLE
(MOD) FastFurnaces: Smokers and Blast Furnaces not allowing villagers to change profession

### ISSUE THREAD

**Issue by JotaEmePM** [The-Nexus-Project/Limitless-3#83]
### Describe your issue, what happened?
This mod makes it impossible to convert villagers into Butchers or Armorers as it replaces the smokers and blast furnaces

### To Reproduce
1. Go to a village.
2. Place a blast furnace or smokers.

### Expected behavior
Villager change profession

### Affected Version
- Pack Version: 1.8.4
- On a server?: No

**Comment by Gbergz** [comment]
Thanks, though this is something that should be reported to the mod developer instead. Gets it fixed faster.

**Comment by Gbergz** [comment]
Fixed next update!
