### ISSUE TITLE
When attacking Zebra, if you right click to swing offhand, it feeds main hand to the zebra

### ISSUE THREAD

**Issue by kulflame** [The-Nexus-Project/Limitless-3#84]
When attacking a zebra I had tetra greatsword in main hand and shortblade in off hand. Right clicked to attack with offhand first and it fed my main hand to the Zebra and disappeared. I have video of this if needed.

**Comment by Gbergz** [comment]
I'm guessing the Zebra is from this mod [BetterDefaultBiomes](https://www.curseforge.com/minecraft/mc-mods/better-default-biomes)

Report it on their issue tracker. Makes sure it gets fixed.

**Comment by Gbergz** [comment]
Closing this for now.

**Comment by kulflame** [comment]
I submitted it on their GitHub. 


Sent from Yahoo Mail for iPhone


On Thursday, January 14, 2021, 9:11 AM, Gbergz <notifications@github.com> wrote:




Closing this for now.
