### ISSUE TITLE
Jacaranda Boat crashes game

### ISSUE THREAD

**Issue by Itwasmer** [The-Nexus-Project/Limitless-3#85]
### Describe your issue, what happened?
Placing a Jacaranda boat into the water crashed client for all players on server, cannot log back into server where jacaranda boat was placed in water. 
Repeated process on single player, oak boats worked fine, but Jacaranda once again crashed client in single player.

### Affected Version
1.8.5

**Comment by Gbergz** [comment]
No info? No logs, no crash reports? Need those

**Comment by Commander-King** [comment]
This is an issue with all "Oh, the biomes you'll go" boats. It's an insta-crash and easily replicable on single player. Here's three back-to-back crashes from this issue. 

[crash-2021-01-11_15.33.37-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5804610/crash-2021-01-11_15.33.37-client.txt)
[crash-2021-01-11_15.40.57-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5804611/crash-2021-01-11_15.40.57-client.txt)
[crash-2021-01-11_15.55.26-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5804613/crash-2021-01-11_15.55.26-client.txt)

**Comment by Gbergz** [comment]
https://github.com/CorgiTaco/BYG/issues

**Comment by Commander-King** [comment]
Oh, also a note on the BYG boat issue -- they did not cause any issues in 1.8.4 when I was playing a few days ago, it's only been after the update that this has happened.

**Comment by Gbergz** [comment]
Probably related to latest changes in Forge.
Along with all other issues that are happening.

Can anyone try to revert forge to forge-35.1.28 and see if the byg boat crash issue persists?

**Comment by choekstr** [comment]
Add an Aspen boat to the list, thus potentially all BYG boats.  When my 1 user got within 2 chunks of the placed boat they crashed.  No one else on the server crashed, so it seems maybe a proximity aspect.

**Comment by Gbergz** [comment]
It's all boats. And it's not tied to forge version. Just tried on 35.1.28. Same crash there. Some mod update must've broken something.

**Comment by Commander-King** [comment]
> 
> 
> Add an Aspen boat to the list, thus potentially all BYG boats. When my 1 user got within 2 chunks of the placed boat they crashed. No one else on the server crashed, so it seems maybe a proximity aspect.

That's true, I had forgotten that proximity is an issue. When I thought it was just me I asked another player to go break the boat and when they got close enough they also crashed. obviously in a single player world this is a moot point though.

**Comment by Gbergz** [comment]
Seems to have fixed itself by updating mods indev for me.
So. It'll be fixed next update. Might even push one out later today.

**Comment by Commander-King** [comment]
For anyone looking for a fix for this until there's an official update, download the most recent version of 'Oh the biomes you'll go' here https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files 
and replace your old jar with the new one! :)
![2021-01-12_13 33 37](https://user-images.githubusercontent.com/48187703/104377240-08f86680-54db-11eb-9995-6289659373e5.png)
