### ISSUE TITLE
Modpack crash version 1.8.5

### ISSUE THREAD

**Issue by Bent0nn** [The-Nexus-Project/Limitless-3#87]
Hello i write my problem here :

Since the 1.8.5 version my modpack crash a result of 3-4 mods  which are
- Alexmobs
- Simplefarming
- Productivebees
I have to desactivate it for playing :/
I post here the crash ;
https://sendeyo.com/show/653feefc4e ---> Simplefarming
https://sendeyo.com/show/72a8bef616 ---> alexmobs
https://sendeyo.com/show/a4ad461444 ---> productivebees

if it can help you or nobody have already this crash ^^

**Comment by Gbergz** [comment]
can you use normal paste sites such as https://hatebin.com/?

**Comment by Bent0nn** [comment]
https://hatebin.com/umkrpmswql -  alexmobs 
https://hatebin.com/qdqhjnmysq - productivebees
 and simplefarming i have post the crash on your discord ^^

**Comment by Gbergz** [comment]
Do you have the complete logs when these crashes happen?

**Comment by Gbergz** [comment]
Closing this, update pack to 1.9.0. If it happens again, feel free to re-open.
