### ISSUE TITLE
remove unused configs

### ISSUE THREAD

**Issue by Dryelo** [The-Nexus-Project/Limitless-3#89]
### Describe your issue, what happened?
Not really a bug, just some unused config files.

### To Reproduce
download the newest modpack (serverfiles) and look into the config folder

### Expected behavior
remove config files when mods are removed from pack

### Crash Reports & Logs (Don't paste entire crash reports here.)
I found the following config files which are definitely from mods which were removed from the pack:

<adlods>
adlods-client.toml
adlods-common.toml
artifacts-common.toml
BetterBedrockGenerator.toml
collective-common.toml
doubleslabs-client.toml
excavation-common.toml
excavation-groups.json
pixelpowers.toml
snowundertrees-common.toml
toughnessbar-client.toml

two more I couldn't identify:
dummmmmmy-client.toml
quarryplus-common.toml

### Affected Version
1.85a

**Comment by Gbergz** [comment]
Left over config files from previous pack versions. Will clean up in the future. Not really on the radar atm. Thanks for the report though.

Edit: I will however remove the configs you mentioned. :)
