### ISSUE TITLE
Bigger Reactors DUMPS fuel after restarts 

### ISSUE THREAD

**Issue by Zelioth** [The-Nexus-Project/Limitless-3#90]
While playing on the server for the past few weeks I have come to notice that my favorite mod "BIGGER REACTORS" completely dumps it's Uranium after a server restart.  I would place 64 ingots or more inside of it and after a scheduled restart or Crash the Reactor would be completely empty.  

I tested this to be sure it wasn't running out while i was online earlier today.  i placed a stack or ingots inside the reactor and 5 minutes later after a restart the reactor was empty, my ingots were gone, and It did not generate any Cyanite Ingots from the Waist of Running. 

I have burned through roughly 20 stacks of Uranium Ingots because of this issue and only created 2 stacks of Cyanite Ingots. I should have half as many Cyanite Ingots by now atleast.

**Comment by RogueLogix** [comment]
Unable to reproduce
