### ISSUE TITLE
Add Silent Mechanism's "Coal Generator" to the loot bag Block list

### ISSUE THREAD

**Issue by DannyR94** [The-Nexus-Project/Limitless-3#92]
The Coal Generator is blocked/unable to be crafted by default however it can still be obtained from loot bags. Placing it down crashes the server and will keep crashing it every time the chunk containing the item is loaded.

**Comment by Gbergz** [comment]
I'm assuming you're playing on the official server. The recipe is only disabled there. Also: https://github.com/The-Nexus-Project/Limitless-3/issues/74

**Comment by DannyR94** [comment]
No, it was on a different server. I didn't see that someone already made a post about it, Thank you!

**Comment by Gbergz** [comment]
Ah gotcha, just tested placing the Coal Generator from Silent's in my test environment and it doesn't crash anymore. Might've gotten fixed in 1.9.0. Try it.

https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3171926
