### ISSUE TITLE
Entity render crash

### ISSUE THREAD

**Issue by Commander-King** [The-Nexus-Project/Limitless-3#93]
The last thing I clicked on/tried to use was the RFtools screen and/or screen controller. I was trying to get the controller to pick up the nearby screen and was clicking back and forth, I think I had just sneak-Rclicked into the screen itself to check the modules when I crashed to desktop. I tried just loading back in but it hard crashes every time. It's also not a full server crash as the other members are still on. (I warned them to stay away from my base)

I am playing on a server running 1.8.5, we updated BYG to 1.1.7 BETA 2 to fix the boat crashing issue, but it's otherwise unmodified. I am not running optifine or any other changes

[crash-2021-01-17_18.29.05-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5827512/crash-2021-01-17_18.29.05-client.txt)
[crash-2021-01-17_18.37.59-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5827513/crash-2021-01-17_18.37.59-client.txt)
[crash-2021-01-17_18.45.10-client.txt](https://github.com/The-Nexus-Project/Limitless-3/files/5827514/crash-2021-01-17_18.45.10-client.txt)

**Comment by Gbergz** [comment]
Did you click the TrueType font ? It's known to crash the game if clicked.

**Comment by Gbergz** [comment]
Try updating the pack to 1.9.0
