### ISSUE TITLE
Server is lagging 1.16.4

### ISSUE THREAD

**Issue by AugustDoctor** [The-Nexus-Project/Limitless-3#94]
I am hosting the server with 8 G of ram and using a client with 10 G of ram. I have up to 3 other people playing at the same time as me and it has been fine until today when it was suddenly lagging by 9 to 10 seconds. Like I said it was fine until we started today and it has made exploration and mining, pretty much the whole pack, impossible to play.

**Comment by AugustDoctor** [comment]
My pc has 32 G of ram btw

**Comment by Gbergz** [comment]
Are you sure your pc is powerful enough to handle a server + a client? That's pretty taxing could be why its lagging.

**Comment by AugustDoctor** [comment]
Actually after restarting the server everything was fine. I think it was just having a rough time for some reason. If it happens again I'll let you know.

**Comment by Gbergz** [comment]
Ah alright, well I'll close this for the time being then. Re-open it or just comment here if needed.

**Comment by choekstr** [comment]
I would add that pretty much every day I have to restart the server as my beefy dedicated server (Ryzen 3950 32core with 10Gb allocated of 128GB and 2TB PCI 4.0 NVME drives) goes from perfect 20 tps to 3.5-4 tps!  

The first time this happened (2nd day of server being up, or ~24 hours later, I was exploring the nether and came back to the overworld to get the achievement for travelling 7x in the overworld via the nether.  It immediately started lagging once I hit the overworld dimension.

The second time it happened is when the 5 of us went to the end, killed the end dragon, explored the end islands and someone died (jetpack ran out of fuel) and they were teleported to the overworld.  It was like a light switch was flicked and we immediately started lagging so bad we had to restart to server to continue to play.

The third time, 1 user went to the bumblezone (again, dimension change) and when they came back the server went from solid 20 tps to 3-4 tps.

Last night I wasn't on so not sure what the 2 users were doing but they pinged me on discord to say the server's tps tanked.  

I am literally working on an auto-restart mod to see if that will help the issue; maybe regular restarting of the server?  Maybe it's the dimensional transferring?  I have so far been chalking it up to early days of 1.16 mods and weirdness but just wanted to document this as well.

**Comment by Gbergz** [comment]
The Official Server restarts once every 4 hours. Just to give you some insight.

**Comment by choekstr** [comment]
that's probably why it isn't seen on the official server.  I'm betting a forge problem and anxious to get everyone up to 1.9/1.16.5 to see if it fixes the issue.

**Comment by AugustDoctor** [comment]
Do we have an estimate for the 1.9 server pack?

**Comment by Gbergz** [comment]
Oh the server lags alright, 6-10 tps. But thats usually due to vanilla issues, 150+ chunks loaded at all times. And it being pretty active.

**Comment by Gbergz** [comment]
> @AugustDoctor Do we have an estimate for the 1.9 server pack?

Nope, when CurseForge accepts 1.16.5 library files it'll be available.
