### ISSUE TITLE
Nether world not working

### ISSUE THREAD

**Issue by ghost** [The-Nexus-Project/Limitless-3#95]
Not using Optifine
### Describe your issue, what happened?
Can't go into nether after updating to 1.90

### To Reproduce
1. Create a portal to nether
2. Light it up
3. Stay inside of it

### Expected behaviour
Should enter nether
### Screenshots
![image](https://user-images.githubusercontent.com/45406683/105035885-fdb5b580-5a5b-11eb-82ad-3c69344b934c.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
Tried to delete nether and end from the server but can't because the server wouldn't startup

### Affected Version
- Pack Version: 1.90
- On a server?: Yes (done by myself, because server pack not released yet)

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-3/issues/37

But for 1.9.0

Edit: I updated the guide to make little more sense.
