### ISSUE TITLE
No Nether or End Dimension

### ISSUE THREAD

**Issue by Forluce** [The-Nexus-Project/Limitless-3#97]
### To Reproduce
Try and enter Nether or End portal.  

### Expected behavior
Teleport to respective dimension.

### Info
Friend and I manually updated from 1.8.5 to 1.9 and kept our server.  On the previous version I was able to enter the Nether, but now I am unable to and am also unable to enter the End.  We have tried resetting the Nether and End multiple times by deleting the Dim-1 and Dim1 folders, but that has not worked.
### Affected Version

- Pack Version: 1.9.0
- On a server?: Yes

**Comment by Forluce** [comment]
Found out the issue, for some reason the level data was missing the nether and end dimensions.  Manually added them back in.

**Comment by Gbergz** [comment]
Yeah, you could've also followed this, but glad you got it sorted.
https://github.com/The-Nexus-Project/Limitless-3/issues/37
