### ISSUE TITLE
Quark Amber recipes not working.

### ISSUE THREAD

**Issue by 64thParaDux** [The-Nexus-Project/Limitless-3#99]
### Describe your issue, what happened?
Tried both variants not working 

### To Reproduce
Try both recipes, also -3006 72 -2995 om official server it is not working.

### Expected behavior
Should make amber

### Affected Version
- Pack Version: 1.9
- On a server?: Official

**Comment by Gbergz** [comment]
Now when I have the time, I can't find any "amber" in Quark.
